### ISSUE TITLE
SQL CE Update() cannot use columns from table within SET

### ISSUE THREAD

**Issue by sunib** [zzzprojects/EntityFramework-Plus#129]
I'm using the brandnew support for SQL CE in my application. There is one query that I don't get translated to the update function.

This is the code that I'm using:
```
context.Transacties
                .Where(t => t.MutatieId.HasValue && t.MutatieId.Value == mutatieId)
                .Update(t => new Transactie()
                {
                    Units = t.Bedrag / 0.005,
                    RecordInfo_ModifiedBy = context.Username,
                    RecordInfo_ModifiedOn = DateTime.Now
                }, bu => bu.Executing = b => Console.WriteLine(b.CommandText));
```

This is the query that is generated:
```
UPDATE [Transactie]
SET [Units] =  
    B.[Bedrag] / 0.005 ,
[RecordInfo_ModifiedBy] = @zzz_BatchUpdate_1,
[RecordInfo_ModifiedOn] = @zzz_BatchUpdate_2
WHERE EXISTS ( SELECT 1 FROM (SELECT 
    [Extent1].[Id] AS [Id], 
    [Extent1].[MutatieId] AS [MutatieId], 
    [Extent1].[Bedrag] AS [Bedrag], 
    [Extent1].[Units] AS [Units], 
    [Extent1].[RecordInfo_ModifiedBy] AS [RecordInfo_ModifiedBy], 
    [Extent1].[RecordInfo_ModifiedOn] AS [RecordInfo_ModifiedOn]
    FROM [Transactie] AS [Extent1]
    WHERE ([Extent1].[MutatieId] IS NOT NULL) AND ([Extent1].[MutatieId] = @p__linq__0)) AS B
               WHERE [Transactie].[Id] = B.[Id]
           )  
```

This gives me the following SqlCeException:
```
The column name is not valid. [ Node name (if any) = B,Column name = Bedrag ]
```

Would it be possible to get this working? Using values from the table within the SET would be very usefull.

**Comment by JonathanMagnan** [comment]
Hello @sunib,

Unfortunately as specified in the issue #124, SQL Compact support is more limited.

This code works fine under SQL Server since a JOIN is used instead of the EXISTS statement. However, SQL Compact doesn't support JOIN in the update statement.

However, it may still be possible to support some case like this one (but not all) by using some sub-query. I will give it a try tomorrow.

Best Regards,

Jonathan

**Comment by sunib** [comment]
Did you had any change to look into the issue?

**Comment by JonathanMagnan** [comment]
Hello @sunib ,

Sorry for the delay, unfortunately, time was missing, but I will for sure put this request in high priority for this weekend.

You should get a fix for next Monday.

Best Regards,

Jonathan

**Comment by sunib** [comment]
Ok, I'm looking forward for it.

Op di 28 feb. 2017 19:26 schreef Jonathan Magnan <notifications@github.com>:

**Comment by JonathanMagnan** [comment]
Hello @sunib ,

The v1.4.32 has been released.

Let me know if that's working.

Be "careful" (it should not happen), starting from this version, you cannot concatenate hard coded string anymore containing the value "B.[" otherwise the "B." will be replaced by an empty string.

Example:

```csharp
ctx.EntitySimples.Where(x => x.ColumnInt < 2)
	.Update(x => new EntitySimple() {ColumnString = x.ColumnString + " B.[ Seriously?"});
```

Could you also contact me directly info@zzzprojects.com ? I would like to ask your feedback concerning the future of this library.

Best Regards,

Jonathan

**Comment by sunib** [comment]
This is very nice, I just tested it and all my queries work now. Thank you very much @JonathanMagnan !

Regarding your last question I shall contact you by e-mail. Have a great weekend.
