### ISSUE TITLE
Z.EntityFramework.Plus.EFCore 1.2.0 is not compatible with netcoreapp1.0

### ISSUE THREAD

**Issue by xbuilder** [zzzprojects/EntityFramework-Plus#14]
package restore  failed:

Package Z.EntityFramework.Plus.EFCore 1.2.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Z.EntityFramework.Plus.EFCore 1.2.0 supports:
      - net451 (.NETFramework,Version=v4.5.1)
      - netcore50 (.NETCore,Version=v5.0)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.

**Comment by zzzprojects** [comment]
Thank you,

We believe this issue is due to not having a version for netstandard1.3 which was not required in RC1.

Can you send us (info@zzzprojects.com) the "framework" section of your project.json (You can remove almost everything, we just want to know which framework your project support)? We will make sure to support it before releasing the next version

We will read more on this subject this weekend and fix it at the start of next week.

**Comment by xbuilder** [comment]
```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0-rc2-3002702",
      "type": "platform"
    },
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-rc2-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview1-final",
    "Z.EntityFramework.Plus.EFCore": "1.2.0"
  },

  "tools": {
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": [
        "portable-net45+win8+dnxcore50",
        "portable-net45+win8"
      ]
    }
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  }
}
```

**Comment by zzzprojects** [comment]
Hello xBuilder,

We fixed the package in the version v.1.2.3

Let us know if everything is now working on your side.

**Comment by xbuilder** [comment]
Yes,it works :+1:

**Comment by zzzprojects** [comment]
Confirmed
