### ISSUE TITLE
Add support for EF CORE InMemory DataContext for unit testing.

### ISSUE THREAD

**Issue by skorunka** [zzzprojects/EntityFramework-Plus#15]
This is how I create a DbContext for unit tests:

		protected static DbContextOptions<T> CreateNewInMemoryDbContextOptions<T>()
			where T : DbContext
		{
			var serviceProvider = new ServiceCollection()
				.AddEntityFrameworkInMemoryDatabase()
				.BuildServiceProvider();

			// Create a new options instance telling the context to use an
			// InMemory database and the new service provider.
			var builder = new DbContextOptionsBuilder<T>()
				.UseInMemoryDatabase()
				.UseInternalServiceProvider(serviceProvider);

			return builder.Options;
		}

             var newTestDbContext = new TestDbContext(CreateNewInMemoryDbContextOptions<TestDbContext>())

While executing:

newTestDbContext.Entities.Where(x => x.Id > 1).Delete();

I get Exception:

   at Z.EntityFramework.Plus.InternalExtensions.GetDbContext[T](IQueryable`1 source)
      at Z.EntityFramework.Plus.BatchDelete.Execute[T](IQueryable`1 query)
.....
   Result Message:	Unable to cast object of type    'Microsoft.EntityFrameworkCore.Query.Internal.InMemoryQueryContextFactory' to type 'Microsoft.EntityFrameworkCore.Query.Internal.RelationalQueryContextFactory'.

**Comment by zzzprojects** [comment]
Thank you for reporting this issue.

Most of our feature like Batch Delete has been designed to work with a relational database like SQL Server, MySQL, etc.

We will look at the beginning of next week if we can support InMemory provider as well.

**Comment by zzzprojects** [comment]
Hello skorunka,

We successfully implemented this feature however we have a major concern about it.

Our library is designed for supporting relational database with real SQL. While implementing this feature was a piece of cake for Query Delete, other features like Query Update, Query Future might be way harder and near impossible. We don't know yet if we want to start to support some InMemory features because once we start supporting one, we are afraid people will ask for more features.

We will take our decision today and release either a new version or send you the code for this feature tomorrow.

**Comment by zzzprojects** [comment]
Hello skorunta,

The version v1.3.1 has been released supporting InMemory database for Batch Delete feature.

You will need to specify a factory in order to enable this feature. You can view an example here:
[Batch Delete - EF Core InMemory](https://github.com/zzzprojects/EntityFramework-Plus/wiki/EF-Batch-Delete-%7C-Entity-Framework-Batch-Delete-Objects-Without-Loading-Them#ef-core-inmemory)

We finally choose to support it and add other feature when they will be requested.

**Comment by zzzprojects** [comment]
Closing: Fixed in v1.3.1

**Comment by skorunka** [comment]
Thank you!

**Comment by vmachacek** [comment]
Hello, I'm currently using version `1.4.37` and I'm having the error as described in the header of an issue. It is during a call `UpdateAsync` method. Can you give me some status update on this one, please?

**Comment by JonathanMagnan** [comment]
Hello @vmachacek ,

Could you open a new issue?

I'm not sure if we will be able to fix it since InMemory database work very differently than Relational Database but we will sure give it a try this week.

Best Regards,

Jonathan

**Comment by vmachacek** [comment]
Here is the new issue - https://github.com/zzzprojects/EntityFramework-Plus/issues/149#event-1027613632
