### ISSUE TITLE
Ideas for support EF Core Include Filter

### ISSUE THREAD

**Issue by Jonatthu** [zzzprojects/EntityFramework-Plus#156]
I have the next snippet from microsoft site. 

```
   var blog = context.Blogs
        .Single(b => b.BlogId == 1);

    var goodPosts = context.Entry(blog)
        .Collection(b => b.Posts)
        .Query()
        .Where(p => p.Rating > 3)
        .ToList();
```

In my project one way that I'm using this is

```
IQuerable<Users> query = base.dbSet;
var users = query.Where(x => x.Active).ToList(); // Call all the users active = 1 from db executed.
foreach (var user in users) {
   base.dbContext.Entry(user)
       .Collection(x => x.Posts)
       .Query()
       .Where(x => x.Active)
       .ToList(); // Executed 
}

return users;
```
To implement the current IncludeFilter for EF Core in the case of Lists navigation properties this is the way, for normal navigation properties I am not sure but currently what is the current status of the implementation of IncludeFilter for EF Core, What are the impediments? I want to help

**Comment by JonathanMagnan** [comment]
Hello @Jonatthu ,

Unfortunately, we "cannot" support it until EF Core team fix the N+1 Issue.

You can find our answer to a similar question here: http://stackoverflow.com/questions/43467133/entity-framework-core-include-with-filter/43472202#43472202

## N+1 Queries Issue
Our Library doesn't support Query Filter yet for .NET Core due to the N+1 queries issue.

Under our hood for EF5 && EF6, our library was only doing a simple projection.

Something similar to this using your information:

```csharp
var users = _Context.Users.Select(x => new {
				Users = x,
				Childs = x.Childs.Any(ec => ec.Id > 1)
			})
			.ToList()
			.Select(x => x.Users)
			.ToList();
```

However, for EF Core, the same projection make a database roundtrip to get child for every users (N+1 queries)

You can try the following projection and see if you get the same error.

I believe until the EF Core team fix it, from my knowledge, there is not a way (of I'm aware) to filter child entities.

```sql
SELECT [x].[Id], [x].[ColumnInt]
FROM [Lefts] AS [x]
go
exec sp_executesql N'SELECT CASE
	WHEN EXISTS (
		SELECT 1
		FROM [Rights] AS [ec1]
		WHERE ([ec1].[Id] > 1) AND (@_outer_Id1 = [ec1].[LeftId]))
	THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END',N'@_outer_Id1 int',@_outer_Id1=1
go
exec sp_reset_connection
go
exec sp_executesql N'SELECT CASE
	WHEN EXISTS (
		SELECT 1
		FROM [Rights] AS [ec1]
		WHERE ([ec1].[Id] > 1) AND (@_outer_Id1 = [ec1].[LeftId]))
	THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END',N'@_outer_Id1 int',@_outer_Id1=2
go
exec sp_reset_connection
go
exec sp_executesql N'SELECT CASE
	WHEN EXISTS (
		SELECT 1
		FROM [Rights] AS [ec1]
		WHERE ([ec1].[Id] > 1) AND (@_outer_Id1 = [ec1].[LeftId]))
	THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END',N'@_outer_Id1 int',@_outer_Id1=3
go
exec sp_reset_connection
go
exec sp_executesql N'SELECT CASE
	WHEN EXISTS (
		SELECT 1
		FROM [Rights] AS [ec1]
		WHERE ([ec1].[Id] > 1) AND (@_outer_Id1 = [ec1].[LeftId]))
	THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END',N'@_outer_Id1 int',@_outer_Id1=4
go
exec sp_reset_connection
go
exec sp_executesql N'SELECT CASE
	WHEN EXISTS (
		SELECT 1
		FROM [Rights] AS [ec1]
		WHERE ([ec1].[Id] > 1) AND (@_outer_Id1 = [ec1].[LeftId]))
	THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END',N'@_outer_Id1 int',@_outer_Id1=5
go
```

**Comment by Jonatthu** [comment]
Thanks for the fully detail answer.
Anyway seems like EF Core is the problem then.
What about his snippet? Is not one round trip to the database but can do the work until EF Core team fix that problem https://github.com/aspnet/EntityFramework/issues/1833#issuecomment-262741637

**Comment by JonathanMagnan** [comment]
Hello @Jonatthu ,

I have takes some time checking about Include Filter today.

The provided snippet miss a lot of code and if I understood was intended to work if EF6

Currently, no matter what I try, I always end up by getting a N+1 query issue. 

Even a simple Select

```csharp
var parents = ctx.Parents.Select(x => x.Childs).ToList();
```

Create N queries!!!

I believe the only option remaining is "hacking" directly the Include method since other workarounds create way to much queries.

**Comment by Jonatthu** [comment]
Can the Include Filter work with entity framework core even if has N queries?
You can pre release that until EF Core has that fixed, or is more complex than that?
@JonathanMagnan

**Comment by JonathanMagnan** [comment]
Yes, it probably can... under a new name like QueryFilterVerySlow or something similar to this ;) I don't want people to get mad at me!!!

**Comment by Jonatthu** [comment]
hahahaha @JonathanMagnan  that's very funny, for a big production project so you recommend me to use EF Core and deal with this problems without IncludeFilter until EF Core 2 comes in, or start with EF 6?

**Comment by JonathanMagnan** [comment]
Unfortunately, I cannot recommend EF Core.

-	Doesn’t support simple cast method
-	Doesn’t “support” simple select method (N queries is not supporting)
-	Doesn’t complex type and some hierarchy 
-	Have less way documentation
-	Have less third party project
-	And more…

On my side, it’s even worse since after every release it breaks my code because I use some method specific to Entity Framework that should not be used ;)

Things will get better but how many months till EF Core V2.x get stable? One more year?

As you know, EF Core is a complete revamp on .NET  Core and still very young... Some people say it's like when the .NET Framework 1.1 was released, it was working but not as mature as the .NET Framework 2.0 was!

So will you recommend someone to code on the .NET Framework 1.1 over the .NET Framework 4.0? That's a very similar question you are currently asking ;)

It works but...

**Comment by JustMaier** [comment]
@JonathanMagnan now that EF Core 2.1 is out and they've [improved/fixed the "N+1" query issue](https://blogs.msdn.microsoft.com/dotnet/2018/05/30/announcing-entity-framework-core-2-1/#optimization-of-correlated-sub-queries), is this something you'd be willing to take a look at?

**Comment by JonathanMagnan** [comment]
Hello @JustMaier ,

Unfortunately, we already tried it with EF Core 2.1 and it was still not working.

We will announce soon a new product on our side: EF Classic

Basically, it will be EF6 but that also support .NET Core. So this kind of feature will be easier to implement on our side since we will no longer be limited of being only a third party libraries ;)

Best Regards,

Jonathan

**Comment by JustMaier** [comment]
Bummer. They're making progress with EF Core, but they've still got a ways
to go.

That said, I'm excited about the new product. Thanks for the update!

**Comment by cyptus** [comment]
are there any updates to this? ef core 3.0 is released now and the n+1 issue seems to be fixed

**Comment by JonathanMagnan** [comment]
Hello Cyptus,

The EF Core `IncludeFilter` is already available since a few months. I forget to answer this Issue.

Best Regards,

Jonathan
