### ISSUE TITLE
Seemingly inefficient queries generated for simple IncludeFilter() scenario

### ISSUE THREAD

**Issue by mcdonams** [zzzprojects/EntityFramework-Plus#167]
I am wiring up some queries and trying to use the IncludeFilter() to limit the results in a child collection.  In my most basic case, I can’t make sense of the SQL that is being returned.  The query returns more results than are necessary, and though it’s not a major problem in this example, in cases when we are pulling a large set of records, the additional records will hurt performance.  Here is the scenario:

We have 2 tables, in a one-to-many relationship:

Contacts
ContactNotes

As an initial POC, I am trying to pull the most recent ContactNote for each Contact.  Here are 2 examples:

1)	Pull a single contact, and the most recent note:

```
IQueryable<Contact> query = _db.Contacts
       	.IncludeFilter(c => c.ContactNotes.OrderByDescending(n => n.ContactNoteId).Take(1))
       .Where(c => c.ContactId == 1);
```

The generated SQL query returns what I would expect: a single row, with Contact columns first, followed by columns for the most recent ContactNotes record.

2)	Pull a list of contacts, and the most recent note for each:
```
var contactIds = new List<int>() { 1, 2, 3 };

IQueryable<Contact> query = _db.Contacts
    	.IncludeFilter(c => c.ContactNotes.OrderByDescending(n => n.ContactNoteId).Take(1))
        .Where(c => contactIds.Contains(c.ContactId));
```

I would think this query could be written in such a way as to retrieve only 3 rows, much like the previous example.  However, I get 9 rows of data.  Again, this isn’t a major deal here, but when I am returning thousands of records, and including additional tables, the extra overhead is a problem.

I assume I am using this correctly, so just wanted to get your thoughts on this.  Thanks!

[Query2.txt](https://github.com/zzzprojects/EntityFramework-Plus/files/1059039/Query2.txt)
[Query1.txt](https://github.com/zzzprojects/EntityFramework-Plus/files/1059040/Query1.txt)

**Comment by JonathanMagnan** [comment]
Hello @mcdonams ,

Unfortunately, we don't create the SQL query, we only create a project and get the result from the SQL generated by Entity Framework.

I suggest you to use instead `IncludeOptimized` instead of `IncludeFilter`. You can also filter the Include part.

[Wiki - Include Optimized](https://github.com/zzzprojects/EntityFramework-Plus/wiki/EF-Query-IncludeOptimized-%7C-Entity-Framework-Filter-Child-Collections-and-Optimize-Include)

By using the IncludeOptimized, 6 rows will be returned. 3 rows for the contact and 3 rows for the contact notes.

So if you need to return 1000 contact, 2000 rows will be returned in your example.

Let me know if this suggestion is good for your scenario.

Best Regards,

Jonathan

**Comment by mcdonams** [comment]
Thanks for the response!  I'll take a look at IncludeOptimized() and see how it fits as well.
