### ISSUE TITLE
IncludeOptimized skips our cache TransactionInterceptor and Provider

### ISSUE THREAD

**Issue by sebastianroesch** [zzzprojects/EntityFramework-Plus#18]
We are using a custom, multi-tenant implementation of EFCache (https://efcache.codeplex.com/) as our cache provider for memory and Redis. Since we added EF-Plus, and in particular IncludeOptimized, we noticed that caching no longer works.

EFCache seems to skip the TransactionInterceptor and Provider pipeline used by EFCache.

As far as I can tell, the following section in EF-Plus executes the queries:

```
var interceptionContext = Context.GetInterceptionContext();
using (var reader = DbInterception.Dispatch.Command.Reader(command, new DbCommandInterceptionContext(interceptionContext)))
{
     foreach (var query in Queries)
     {
           query.SetResult(reader);
           reader.NextResult();
      }
}
```
I'm not sure what the interception context is exactly, but is there a way that I can make EF-Plus use the EFCache transaction interceptor and cache the individual queries?

Thanks, Sebastian

**Comment by zzzprojects** [comment]
Hello Sebastian,

The InterceptionContext allow using interceptors: https://msdn.microsoft.com/en-us/data/dn469464.aspx#BuildingBlocks.Registering

From what I understand,
EF+ Query IncludeOptimized create a command and call the InterceptionContext in case the user use an interceptor.

In another hand, EFCache, use a custom IDbTransactionInterceptor and DbProviderService. It's not the same as using Interceptors, so it's normal both products are not compatible.

We are currently investigating some solution:

**Solution #1**
Both products are not compatible since EF+ Query InludeOptimized batch all queries in one SQL Statements for even more performance. However, if we run multiple independent SQL using simply LINQ, it should now, in theory, use the EFCache library.

We will take a day to think about all possible solution and try something later today or tomorrow.

**Comment by sebastianroesch** [comment]
Thank you for the quick reply. 

I found out that the EF-Plus Filter, which we are using for SoftDelete, does not work for us. We needed to use it due to compatibility issues with our previous query filter, but it does not apply the filter to child collections and returns deleted entities in child collections. So it seems that EF-Plus does not work for us for two reasons.

**Comment by zzzprojects** [comment]
Hello Sebastian,

We just released the v1.3.34

We successfully make this library compatible with EFCache by adding a new property "AllowQueryBatch". In your case, you want to disable it. It's a little bit slower since one round-trip will be performed for every query instead of only one.

```csharp
QueryIncludeOptimizedManager.AllowQueryBatch = false;
```

Let us know if the EFCache library is now compatible with our library.

**Comment by zzzprojects** [comment]
About the EF+ Query Filter, can you show us an example? We did some test but everything was correctly working.

This feature should not impact at EFCache.

**Comment by sebastianroesch** [comment]
Thank you for the quick reply. I will check the compatibility with EFCache soon.

Our Query Filter is defined like this: 

`ctx.Filter<HQBaseEntity>("IsDeleted", q => q.Where(x => !x.DeletedOn.HasValue));`

It generally works, because the DeletedOn NOT NULL is correctly applied to the WHERE clause when accessing entities like this:

`var nonDeletedDocument = ctx.Documents.Where(d => d.Id == 4101);`

```
SELECT TOP (2) 
    [Extent1].[Id] AS [Id], 
    [Extent1].[ShownDate] AS [ShownDate], 
    [Extent1].[ValidUntilDate] AS [ValidUntilDate], 
    [Extent1].[SentOn] AS [SentOn], 
....
    [Extent1].[UpdatedOn] AS [UpdatedOn], 
    [Extent1].[UpdatedBy] AS [UpdatedBy], 
    [Extent1].[DeletedOn] AS [DeletedOn], 
    [Extent1].[DeletedBy] AS [DeletedBy]
    FROM [dbo].[Document] AS [Extent1]
    WHERE ([Extent1].[DeletedOn] IS NULL) AND ([Extent1].[Id] = @p__linq__0)
-- p__linq__0: '4101' (Type = Int32, IsNullable = false)
```

EF-Plus Query Filter it does not apply our Deleted filter because the filter is not in the WHERE clause when accessing entities like this:

`var nonDeletedPositionLinks = nonDeletedDocument.DocumentPositionToDocuments;`

Here is the query generated by EF-Plus Query Filter when accessing child collections:
SELECT 
    [Extent1].[Id] AS [Id], 
    [Extent1].[Amount] AS [Amount], 
    [Extent1].[Order] AS [Order], 
    [Extent1].[IsCompleted] AS [IsCompleted], 
    [Extent1].[Text] AS [Text], 
....
    [Extent1].[UpdatedOn] AS [UpdatedOn], 
    [Extent1].[UpdatedBy] AS [UpdatedBy], 
    [Extent1].[DeletedOn] AS [DeletedOn], 
    [Extent1].[DeletedBy] AS [DeletedBy]
    FROM [dbo].[DocumentPositionToDocument] AS [Extent1]
    WHERE [Extent1].[DocumentId] = @EntityKeyValue1
-- EntityKeyValue1: '4101' (Type = Int32, IsNullable = false)

**Comment by sebastianroesch** [comment]
Caching with EFCache works now, thank you! The speed is way better and the performance of cache queries is also great.

**Comment by sebastianroesch** [comment]
Hey @zzzprojects , did you manage to look into the QueryFilter issue I mentioned? Is this a bug or expected? Should I open a new issue for that? 
Thanks, Sebastian

**Comment by zzzprojects** [comment]
Hello Sebastian, sorry for the delay,

I have looked at this issue today. Unfortunately, supporting Lazy Loading seem way too much complicated since EF create a proxy class.

I have no idea yet how I could achieve to support this feature, but I will certainly try some more test to see if it's possible or not.

Yes, you can open a new issue so we could close this one since they are not related but I'm not sure if I will ever support it.

**Comment by sebastianroesch** [comment]
Thank you, I created a new issue here: https://github.com/zzzprojects/EntityFramework-Plus/issues/26
