### ISSUE TITLE
Soft delete filter problem with EF Core.

### ISSUE THREAD

**Issue by hikalkan** [zzzprojects/EntityFramework-Plus#19]
I implemented soft delete for EF Core but it not works.

This is my code: https://gist.github.com/hikalkan/4b0df93c8e95b08120e8cb7cd7f7cded

It properly works for EF 6.x but not works EF Core 1.0. Do you have any idea?

Thanks.

**Comment by hikalkan** [comment]
It works for .NET 4.6.1 but not works for .NET Core 1.0

**Comment by zzzprojects** [comment]
Thank you for reporting.

You are right, we did a small mistake under EF Core. A new version should be available very soon

**Comment by zzzprojects** [comment]
The version v1.3.3 is now available.

Let me know if the issue is also fixed on your side.

**Comment by hikalkan** [comment]
Thanks a lot. I'm closing this issue. If I have the issue again, I'll re-open this.

**Comment by ramiglez30** [comment]
@hikalkan  Hi, I'm using Abp version Core with Angular... my global filters ISoftDelete just stopped working.  Any idea why, or where can I look?...

**Comment by JonathanMagnan** [comment]
Hello @ramiglez30 ,

Could you please open a new issue?

It will be easier to track and help you with this problem on a new issue than instead reviving an old one since they may not be related.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_
