### ISSUE TITLE
Filter is sometimes not using parametrized query

### ISSUE THREAD

**Issue by NielsUll** [zzzprojects/EntityFramework-Plus#206]
We are applying a filter to implement business level security.
It mostly works fine, generating queries like
...
        WHERE ... AND ([Extent4].[UserId] = @p__linq__0) AND ([Extent4].[PrincipalPrivilegeType] = @p__linq__1)
    
...

But occasionally, we get queries like 
            WHERE ... ([Extent4].[UserId] = 3) AND ([Extent4].[PrincipalPrivilegeType] = 1)

This is bad since the server will not reuse execution plans between users.

The filter is set up in the MyDbContext constructor like this:

                 var currentUserId = currentUser.Id;
                  this.Filter<SomeResource>(GlobalFilters.SomeResourceFilter,
                        someResources => someResources.Where(
                            resource => resource.AccessRights.Any(
                                right => right.UserId == currentUserId
                                       && right.PrincipalPrivilegeType == requestedResourceAccess)));

UserId is an int and PrincipalPrivilegeType is an enum - currentUser and requestedResourceAccess are passed into the constructor.

I have tried various workarounds suggested on the net ( e.g. replace  "== currentUserId" with 
"== new { Val = currentUserId}.Val" but it didn't help. And the weird thing is that it mostly gets it right? 
I haven't found any patterns in when it does one or the toher

Any suggestions would be most welcome.

**Comment by JonathanMagnan** [comment]
Hello @NielsUll ,

Unfortunately, this is currently a limitation of our library.

Context filter with dynamic value doesn't fully work. The problem is due to Entity Framework that cache the plan and we didn't find any solution yet to solve it without making some major breaking changes to our library.

I recommend you using https://www.nuget.org/packages/EntityFramework.DynamicFilters/ instead.

I believe this library will be merged in EF+ eventually.

Best Regards,

Jonathan

**Comment by NielsUll** [comment]
Thanks for a quick response! I wil try that.
