### ISSUE TITLE
NullReferenceException at Audit.PostSaveChanges

### ISSUE THREAD

**Issue by ctrl-brk** [zzzprojects/EntityFramework-Plus#236]
There was already an issue #108 for this but it's now closed.
I'm still having this in 1.6.8 but it's not consistent. It disappears if you restart the server and then comes back again after some time.

**Comment by JonathanMagnan** [comment]
Hello @ctrl-brk ,

Could you check about this comment:
https://github.com/zzzprojects/EntityFramework-Plus/issues/181#issuecomment-326390676

I believe there is very good chance this issue happen because you specify some global configuration every time on create a context instance which lead to some concurrency exception like this one.

Best Regards,

Jonathan

**Comment by ctrl-brk** [comment]
Thanks. Seems like that could be the issue. I have made suggested changes and will keep an eye on it.

**Comment by JonathanMagnan** [comment]
Closing comment: Seem to be similar issue as #181
