### ISSUE TITLE
DelegateDecompiler with EF-Plus Query Cache

### ISSUE THREAD

**Issue by jonesm13** [zzzprojects/EntityFramework-Plus#290]
We are attempting to add second-level caching to our db reads using EF-Plus. Our entity model is as follows.

```
public abstract class Auditable
{
   public DateTime DateCreated { get; set; }
   public DateTime? DateModified { get; set; }
   [Computed]
   public DateTime LastUpdated => DateModified ?? DateCreated;
}

public class Widget : Auditable
{
}
```

We are chaining the ```FromCache()``` extension next to the DelegateDecompiler (https://github.com/hazzik/DelegateDecompiler) and AutoMapper projection extensions, like so...

```
public async Task<IEnumerable<WidgetModel>> Get(DbContext db)
{
   return db.Widgets.ProjectTo<WidgetModel>().DecompileAsync().FromCacheAsync();
}
```

The following error is produced...

```Oops! A general error has occurred. Please report the issue including the stack trace to our support team: info@zzzprojects.com```

...with the following stack trace...

```
at Z.EntityFramework.Plus.InternalExtensions.GetObjectQuery(IQueryable query)   
at Z.EntityFramework.Plus.QueryCacheManager.GetCacheKey(IQueryable query, String[] tags)   
at Z.EntityFramework.Plus.QueryCacheExtensions.<FromCacheAsync>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()   
at XXX.<Handle>d__1.MoveNext()
```

**Comment by JonathanMagnan** [comment]
Hello @jonesm13 ,

Thank you for reporting.

Looking at the code, it looks to be caused because the external library create a new IQueryable and we could not find the `ObjectQuery` from this third party library.

We will look at it if there is a way for us to retrieve it or not.

Best Regards,

Jonathan

---
_Help us to keep this library free: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Hello @jonesm13 ,

The v1.7.11 has been released.

Our library should be done compatible with `AutoMapper` and the `ProjectTo` method.

Let me know if that work correctly.

Best Regards,

Jonathan

---
_Help us to keep this library free: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by jbogard** [comment]
@JonathanMagnan I'm the maintainer of the the AutoMapper library, anything we could have done to make this work easier for you? We originally tried to chain a Select but had issues with that so we call into the underlying provider instead.

**Comment by JonathanMagnan** [comment]
Hello @jbogard ,

EF+ often only require getting the `ObjectQuery` used for the current queryable.

In this case, the `ObjectQuery` is only required to create the cache key for this feature.

I'm not sure about the compatibility of all other features. I have added a task to look at it and check what's supporting and not with `ProjectTo`

Best Regards,

Jonathan

**Comment by jonesm13** [comment]
Hi @JonathanMagnan Thanks very much - have tested against v1.7.11 and confirm that it works. Grateful thanks.

**Comment by JonathanMagnan** [comment]
Hello,

We have investigated which features currently support `ProjectTo` from AutoMapper:

- Query Cache
- Query Deferred
- Query Filter
- Query Future

However, following features are not supported yet:
- Query IncludeFilter
- Query IncludeOptimized

We checked both of this feature and it could be possible to support it but require currently to much time to make it happen since we need to play with the expression provided to add some filter to the projection expression provided when using `ProjectTo`.

I don't think there is anything you can do right now @jbogard to make it easier on our side since no matter what, we will need to invest too many hours to make it work and I don't have this time right now due to other projects.

This is for sure something we will eventually try to make it happen in the future but not right now.

Best Regards,

Jonathan

---
_Help us to keep this library free: [Donate](http://www.zzzprojects.com/contribute)_
