### ISSUE TITLE
Index Out of Range Question/Bug

### ISSUE THREAD

**Issue by TonyValenti** [zzzprojects/EntityFramework-Plus#301]
Hi All,
I have a database that contains items that I'm replicating from another database.  The table looks like this:

ID (long.  Primary key in remote database)
Updated_At (DateTimeOffset.  Updated timestamp from remote database)
Row_Inserted_At_Ticks (Local time when we got the record.  Primary Key in local database)

Whenever a change is detected in the remote database, the record is copied down to the local database and then old versions of the record are deleted.  Because of concurrency and other factors, I cannot trust that the record I just downloaded is the latest record, so I do the following:

* Group all items by their remote ID
* Order the items in the  groups by their Updated_At descending
* Because the first item in each group is the one we want to keep, skip it and delete all others.

I have this implemented using two queries as follows:
````
var Prune = Query
                .GroupBy(x => x.ID)
                .SelectMany(x => x.OrderByDescending(y => y.Updated_At).Skip(1).Select(id => id.Row_Inserted_At_Ticks))
                ;

            var ToPrune = Prune.ToArray();

            if(ToPrune.Length > 0) {
                this.Query.Where(x => ToPrune.Contains(x.Row_Inserted_At_Ticks))
                    .Delete()
                    ;
            }
````

I'd like to make this one query, but when I run this, I get an Index out of Range exception:
````
var Prune = Query
                .GroupBy(x => x.ID)
                .SelectMany(x => x.OrderByDescending(y => y.Updated_At).Skip(1))
                ;

Prune.Delete();
````
Does anyone have any suggestions on how to deal with this or why I'm getting the exception?

**Comment by JonathanMagnan** [comment]
Hello @TonyValenti ,

Thank you for reporting, we will look why this exception is thrown.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Hello @TonyValenti ,

We started to investigate this issue.

Unfortunately, we didn't success to reproduce the issue.

However, something it weirds, you delete data by `Row_Inserted_At_Ticks`. What about if the latest two of your latest row are inserted at the same time or a row with another ID has been inserted at the same time. Since you delete by date and not using an ID, I believe the whole logic currently have an issue.

If you still have the `index out of range` exception, could you provide us a project example? That will help us to debug this issue.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Hello @TonyValenti ,

This issue will be closed since we haven't heard back from you.

Feel free to reopen it if you can provide the information we asked.

Best Regards,

Jonathan
