### ISSUE TITLE
Batch Update reference value from list item

### ISSUE THREAD

**Issue by hossambarakat** [zzzprojects/EntityFramework-Plus#307]
Hi,
I am trying to use Bulk Update to update table entities and the column value should be used from `List` as should in the following test:

```csharp
[TestMethod]
public void LookupFromArray()
{
    TestContext.DeleteAll(x => x.Entity_Basic_Manies);
    TestContext.Insert(x => x.Entity_Basic_Manies, 50);

    using (var ctx = new TestContext())
    {
        // BEFORE
        Assert.AreEqual(1225, ctx.Entity_Basic_Manies.Sum(x => x.Column1));
       
        // ACTION
        var myList = new List<MyDto>
        {
            new MyDto
            {
                ExternalId = 99,
                Id = 1
            }
        };
        
        ctx.Entity_Basic_Manies.Where(x => x.Column1 > 10 && x.Column1 <= 40).Update(x => new Entity_Basic_Many
        {
            Column1 = myList.FirstOrDefault(y=>y.Id == x.Column1).ExternalId,
        });
        
        // AFTER
        Assert.AreEqual(3430, ctx.Entity_Basic_Manies.Sum(x => x.Column1));
    }
}
```

I am getting the following exception
 `System.NotSupportedException: Unable to create a constant value of type 'Z.Test.EntityFramework.Plus.MyDto'. Only primitive types or enumeration types are supported in this context.`

Are there any way to get the above test passing?

**Comment by JonathanMagnan** [comment]
Hello @hossambarakat ,

The goal of this feature is getting everything executed on the database side. You are currently mixing some code that only exists on the server side (`var myList = new List<MyDto>`)

This kind of error is generated when `Entity Framework` try to generate a `SQL` but it cannot. We have the same limitation as `EF` since we use the SQL they generate.

Unfortunately, there is nothing we can do here to support it.

Best Regards,

Jonathan

**Comment by hossambarakat** [comment]
@JonathanMagnan Thanks a lot for your quick response, I guess my resort now is to write the SQL myself

**Comment by JonathanMagnan** [comment]
Unfortunately for now yes ;(

Best Regards,

Jonathan
