### ISSUE TITLE
Should consider a option to customize date and time timezones for audit dates

### ISSUE THREAD

**Issue by fabianosobreira** [zzzprojects/EntityFramework-Plus#34]
All datetime fields generated are currently bound to the enviroment timezone. This can be a issue with a multi region application running in a server with a diferent timezone.

Consider a option to customize date and time timezones and set the UTC timezone as a default.

**Comment by zzzprojects** [comment]
Hello Fabio,

Are you talking about the CreatedDate or for property value?

**CreatedDate**
A new version will be released to make auditing more customizable.

**Property Value**
You currently can [format value](https://github.com/zzzprojects/EntityFramework-Plus/wiki/EF-Audit-%7C-Entity-Framework-Audit-Trail-Context-and-Track-Changes#format-value) by entity, but your request is probably formatting it by type for all entity. We will look at this issue as well.

We are shipping a new version of the Audit this week, we will try to include your suggestion.

Best Regards,

Jonathan

**Comment by fabianosobreira** [comment]
Yes, the CreatedDate property.

**Comment by zzzprojects** [comment]
Hello Fabio,

The v1.4.0 is now released. You can now easily set your created date.

You can find an example in the Wiki. We choose to let the user specify the CreatedDate (or any other field value) instead of adding a timezone property since it allows more flexibility.

Wiki: [EF+ Audit Customization](https://github.com/zzzprojects/EntityFramework-Plus/wiki/EF-Audit-%7C-Entity-Framework-Audit-Trail-Context-and-Track-Changes#audit-customization)

Let me know if the new version answered to this request.

**Comment by fabianosobreira** [comment]
Nice update. It will solve my request.
