### ISSUE TITLE
use batch update and batch delete

### ISSUE THREAD

**Issue by zhuyangping** [zzzprojects/EntityFramework-Plus#349]
Hi,

I am using MYSQL. I found that the last generated SQL will use inner join. It will cause database row level deadlock. Why use inner join in design?

internal const string CommandTextTemplate_MySQL = @"
UPDATE {TableName} AS A
INNER JOIN ( {Select}
           ) AS B ON {PrimaryKeys}
SET {SetValue}
";

**Comment by JonathanMagnan** [comment]
Hello @zhuyangping ,

Some SQL has been designed this way since we don't control the SQL generated, Entity Framework does. So we have sometimes limited since we need to support multiple scenarios.

The project is open source, feel free to try to provide us a better solution.

Best Regards,

Jonathan

**Comment by zhuyangping** [comment]
I saw your code.
internal const string CommandTextTemplate_MySQL = @"
UPDATE {TableName} AS A
INNER JOIN ( {Select}
) AS B ON {PrimaryKeys}
SET {SetValue}
";

**Comment by JonathanMagnan** [comment]
Hello @zhuyangping ,

This issue will be closed since it has been answered.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
