### ISSUE TITLE
Cache Never Expiring

### ISSUE THREAD

**Issue by rjperes** [zzzprojects/EntityFramework-Plus#35]
Hi,
If I do this:

`ctx.MyEntities.FromCache(new MemoryCacheEntryOptions() { AbsoluteExpirationRelativeToNow = TimeSpan.FromSeconds(10) });`

Then sleep for 2 minutes, I would expect the items to be gone from cache. But they arent:

`var cache = QueryCacheManager.Cache as MemoryCache;
var count = cache.Count; //1`

I know the interval is set to 1 minute.
What am I doing wrong?
Thanks,

RP

**Comment by zzzprojects** [comment]
Hello RP,

I don't think there is a bug here.

Unfortunately, you cannot believe the cache count under .NET Core since it also counts expired items until they are scanned to be removed.

 **By example**, even if the cache count = 1, the expired item cannot be longer retrieved.


```csharp
using (var ctx = new TestContext())
{
    var memoryCache = (QueryCacheManager.Cache as MemoryCache);

    // Cache
    ctx.Entity_Basics.FromCache(new MemoryCacheEntryOptions() { AbsoluteExpirationRelativeToNow = TimeSpan.FromSeconds(1) });
    var cacheKey = QueryCacheManager.GetCacheKey(ctx.Entity_Basics, new string[0]);
           

    var cacheCount1 = (QueryCacheManager.Cache as MemoryCache).Count; // return 1
    object item1; // return the list
    var isFound1 = memoryCache.TryGetValue(cacheKey, out item1); // return true
       

    Thread.Sleep(2000);

    var cacheCount2 = (QueryCacheManager.Cache as MemoryCache).Count; // return 1
    object item2; // return null
    var isFound2 = memoryCache.TryGetValue(cacheKey, out item2); // return false
}
```

In short, when you call a method like "TryGetValue", "SetEntry", at the end of the method, it will start to scan for expired items. The default value of _expirationScanFrequency is one minute, so that mean it only remove expired items after a minimum of one minute since the last scan.

```csharp
private void SetEntry(CacheEntry entry)
{
  // ...code...
  this.StartScanForExpiredItems();
}
	
private void StartScanForExpiredItems()
{
  DateTimeOffset utcNow = this._clock.UtcNow;
  if (!(this._expirationScanFrequency < utcNow - this._lastExpirationScan))
	return;
  this._lastExpirationScan = utcNow;
  TaskFactory factory = Task.Factory;
  CancellationToken none = CancellationToken.None;
  int num = 8;
  TaskScheduler @default = TaskScheduler.Default;
  factory.StartNew((Action<object>) (state => MemoryCache.ScanForExpiredItems((MemoryCache) state)), (object) this, none, (TaskCreationOptions) num, @default);
}
```

Let me know if I answered to your question.

Best Regards,

Jonathan

**Comment by rjperes** [comment]
Hi, Jonathan!
Thanks, makes sense! :-)

RP
