### ISSUE TITLE
EFCore 2.1 Crash on UpdateAsync

### ISSUE THREAD

**Issue by guipadua** [zzzprojects/EntityFramework-Plus#376]
I put together sample project here: https://github.com/guipadua/ContosoUniversity.MySql/releases/tag/debug_2018-06-19.1

Setup:

Package|Version
-|-
ASP.NET Core | 2.1.0
Pomelo.EntityFrameworkCore.MySql| 2.1.0-rc1-final
Z.EntityFramework.Plus.EFCore	| 1.7.20

Database version: 

innodb_version | 5.6.36-82.0
-- | --
protocol_version | 10
slave_type_conversions |  
version | 10.1.24-MariaDB
version_comment | mariadb.org binary distribution
version_compile_machine | x64
version_compile_os | Win64
version_malloc_library | system
version_ssl_library | YaSSL 2.4.2

```
NullReferenceException: Object reference not set to an instance of an object.
Z.EntityFramework.Plus.BatchUpdate.CreateCommand(IQueryable query, IEntityType entity, List<Tuple<string, object>> values)
Z.EntityFramework.Plus.BatchUpdate.Execute<T>(IQueryable<T> query, Expression<Func<T, T>> updateFactory)
System.Threading.Tasks.Task<TResult>.InnerInvoke()
System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, object state)
System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref Task currentTaskSlot)
ContosoUniversity.Controllers.CoursesController.UpdateCourseCredits(Nullable<int> multiplier) in CoursesController.cs
-

        [HttpPost]
        public async Task<IActionResult> UpdateCourseCredits(int? multiplier)
        {
            if (multiplier != null)
            {
                ViewData["RowsAffected"] =
                    await _context.Courses.UpdateAsync(x => new Course { Credits = x.Credits * (int)multiplier });
            }
            return View();
        }

        private bool CourseExists(int id)
Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by JonathanMagnan** [comment]
Hello @guipadua ,

Thank you for reporting.

That's due to the `Pomelo` provider that has removed some method we are using.

See the changelog: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/commit/185c1e18b511fd69e64c55f2067b2d8d5a78127a#diff-e90dbcef326cebf70ee6ec17e8ba9776L45

We will investigate what other solutions we have to support our features without methods that have been removed.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by guipadua** [comment]
Thank you! It does work!
