### ISSUE TITLE
Updating a Date Column with BatchUpdate and AddDays

### ISSUE THREAD

**Issue by terryaney** [zzzprojects/EntityFramework-Plus#38]
Something like this:

new JobContext().Jobs.Where( j => j.DateCreated > EntityFunctions.AddDays( DateTime.Today, -1 ) && j.Package != "null" ).Update( j => new Job { DateExpires = EntityFunctions.AddDays( j.DateExpired, 10 ).Value } );

Throws error: "This function can only be invoked from LINQ to Entities.”

If I do not use the EntityFunctions.AddDays() but set to a hard coded value, it works.  But how could I update a batch of dates to 'slide them all forward' (which is a common pattern for our application)?

**Comment by zzzprojects** [comment]
Hello Terry,

At my surprise, I cannot reproduce this issue. It seems to work fine from our side.

Can you tell me the following information
- Entity Framework Version
- Database Provider
- Any other information which could help me to reproduce this issue!

Here is the SQL generated by the BatchUpdate in our environment:
```sql
exec sp_executesql N'
UPDATE A 
SET A.[CreatedDate] =  
     CAST( DATEADD (day, 10, B.[CreatedDate]) AS datetime2) 
    
FROM [dbo].[BatchDeleteContext_Left] AS A
INNER JOIN ( SELECT 
    [Extent1].[Id] AS [Id], 
    [Extent1].[CreatedDate] AS [CreatedDate]
    FROM [dbo].[BatchDeleteContext_Left] AS [Extent1]
    WHERE [Extent1].[CreatedDate] > (DATEADD (day, -1, @p__linq__0))
           ) AS B ON A.[Id] = B.[Id]
',N'@p__linq__0 datetime',@p__linq__0='2016-09-21 00:00:00'
```

**Comment by terryaney** [comment]
Here is my statement:
```
ctx.Jobs.Where( j => j.DateCreated > EntityFunctions.AddDays( DateTime.Today, -1 ) && j.Package != "null" )
	.OrderBy( j => j.DateCreated )
	.Update( j => new Job {
					Group = null,
					DateCreated = EntityFunctions.AddDays( DateTime.Today, 1 ).Value  }
		);
```
EF 6.1.3

SQL LocalDB:

Microsoft SQL Server 2012 (SP1) - 11.0.3000.0 (X64) 
  Oct 19 2012 13:38:57 
  Copyright (c) Microsoft Corporation
  Express Edition (64-bit) on Windows NT 6.2 <X64> (Build 9200: ) (Hypervisor)

**Comment by zzzprojects** [comment]
Thank you,

I successfully reproduced the issue.

The issue is not related to our library but how an expression with an anonymous type is constructed.

There is a huge difference between this two lines

```csharp
EntityFunctions.AddDays( DateTime.Today, 1 ).Value
EntityFunctions.AddDays( j.DateModified, -1 ).Value
```

The first one is a constant (which thrown an error) while the second one varies depending on the parameter so must be evaluated later.

There is no point to use EntityFunction with DateTime.Today when you could simply use directly the AddDay from the DateTime instances.

**Example**
```csharp
ctx.Jobs.Where( j => j.DateCreated > EntityFunctions.AddDays( DateTime.Today, -1 ) && j.Package != "null" )
        .Update( j => new Job {
                    Group = null,
                        DateCreated = DateTime.Today.AddDays(1),
                        DateModified = EntityFunctions.AddDays( j.DateModified, -1 ).Value }
        );
```

Since when you use EntityFunctions, the method fail directly when the expression is created (so doesn't even enter in our library), there is nothing we can really do.

Can you try using directly the DateTime instead and let me know if that work?

**Comment by terryaney** [comment]
You are right.  Coming from the LINQ to SQL world, the whole EntityFunctions (actually now DbFunctions) threw me for a loop.  Closing.
