### ISSUE TITLE
EntitySetName is always NULL

### ISSUE THREAD

**Issue by Feijo** [zzzprojects/EntityFramework-Plus#401]
Environment:

- **.NET Core 2.1**
- **Microsoft.EntityFrameworkCore 2.1.2**
- **Z.EntityFramework.Plus.Audit.EFCore 1.8.5**

Everything is working fine, all changes are being correctly audited and saved into the database, however the EntitySetName field is always NULL. How does it get set?

**DbContext snippet**

```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.ApplyConfiguration(new AuditEntryMap());
    modelBuilder.ApplyConfiguration(new AuditEntryPropertyMap());
    // Other mappings

    AuditManager.DefaultConfiguration.AutoSavePreAction = (context, audit) =>
    {
        var myCompanyContext = (MyCompanyContext) context;
        myCompanyContext.AuditEntries.AddRange(audit.Entries);
    };

    base.OnModelCreating(modelBuilder);
}

public override int SaveChanges()
{
    var audit = new Audit();

    if (_applicationUser?.Username != null)
        audit.CreatedBy = _applicationUser.Username;

    audit.PreSaveChanges(this);
    var rowAffecteds = base.SaveChanges();
    audit.PostSaveChanges();

    if (audit.Configuration.AutoSavePreAction != null)
    {
        audit.Configuration.AutoSavePreAction(this, audit);
        base.SaveChanges();
    }

    return rowAffecteds;
}
```

I had a look at the Z.EF.Plus.Audit.Shared project and apparently the code that sets the EntitySetName only does it for EF5 or EF6, it doesn't do it for EF Core (AuditEntry.cs around line 65).

**Comment by JonathanMagnan** [comment]
Hello @Feijo ,

The problem is the `EntityEntry` doesn't expose the `EntitySet` in `EF Core`. We made some test again today and we still have not found a way to get it.

If you know a way to get this information, we will be happy to implement it in our libraries.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by jamesrokt** [comment]
Looks like you can get the entry's `TableName` (is that is equivalent to `EntitySet`?) from `entityEntry.Metadata.BaseType.Relational().TableName`

**Comment by asulwer** [comment]
any updates on this?  if after 3 years this is still NULL then remove it from the DB for Core users?

**Comment by JonathanMagnan** [comment]
Hello @asulwer ,

We will look at it. At first sight, this is unfortunately still not available in EF Core 5 but I will ask one of my developers to look deeper than my 2min test.

Let hope this is finally available.

**Comment by JonathanMagnan** [comment]
Hello @asulwer, @Feijo , @jamesrokt 

The v5.1.38 has been finally released!!!

Unfortunately, we didn't find any API in EF Core to find the `EntitySetName` but the code we added should cover pretty much most of all scenarios.

If you find a scenario that we still don't support, just give us an example and we will try to support it as well if that's possible.

Best Regards,

Jon
