### ISSUE TITLE
Writing Unit Tests

### ISSUE THREAD

**Issue by KenBonny** [zzzprojects/EntityFramework-Plus#415]
I've been looking for a way to write unit tests against a piece of code that uses the EF+ extensions. More specifically: DeleteFromQuery();

`Context.Permissions.Where(x => x.UserId == userId && x.RoleId == roleId).DeleteFromQuery();`

Every time I run that code in tests, it fails because it can't find the context (_Could not find the context from the IQueryable expression. Are you sure this is coming from an Entity Framework Context?_). Is there a way to use the fake context and not look for the actual context that goes to the database?

**Comment by JonathanMagnan** [comment]
Hello @KenBonny ,

The answer highly depends on which library you use for your unit test.

For example, we support `Effort`: https://entityframework-effort.net/

Which library are you using? We cannot, unfortunately, support them all since we still need to delete it from a context (even if it's a memory context).

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by KenBonny** [comment]
I'm using NUnit and a custom FakeContext that implements my own interface. As in
`public class FakeContext: IApplicationContext {...}`
I'll see if I can use the effort mock to create a custom mock for these tests. Or is there a way to trick EF+ into thinking my fake DbSet is going to the database?

**Comment by JonathanMagnan** [comment]
Hello @KenBonny ,

In short, what's required by our library is normally retrieving the `ObjectQuery` from the query

See: https://github.com/zzzprojects/EntityFramework-Plus/blob/master/src/shared/Z.EF.Plus._Core.Shared/EF5_EF6/IQueryable%60/IQueryable%60.GetObjectQuery.cs

So if you store the `ObjectQuery` into one of the following places:
- `InternalQuery` property
- `inner` field
- `InnerQuery` property
- `ObjectQuery` property

Our library should work.

So the answer highly depend on how you have customized your test with your `FakeContext`

**Comment by KenBonny** [comment]
I've been trying to get this to work, but I can't find a way to mock the ```ObjectQuery``` object. I'm not going to an actual database, just an in memory list, so there is no connection string, no sql can be executed. Can I still trick EF+ into thinking that it's talking to a database without actually having one?

**Comment by JonathanMagnan** [comment]
Is there a way to retrieve the context from the query?

Our code can support some memory database but it doesn't do magic. It simple delete rows from the set, so we need a way to retrieve it.

See the following code: https://github.com/zzzprojects/EntityFramework-Plus/blob/master/src/shared/Z.EF.Plus.BatchDelete.Shared/BatchDelete.cs#L211-L218

**Comment by KenBonny** [comment]
I've used Effort to make it work. Thanks for the help. This can be closed.
