### ISSUE TITLE
EF Core custom query compiler and Future/FutureValue extensions

### ISSUE THREAD

**Issue by vsopko** [zzzprojects/EntityFramework-Plus#422]
When implementing custom query compiler for ef core and then using Future() extension method resulting query returns NullReferenceException: Object reference not set to an instance of an object.
It looks lke Z.EntityFramework.Plus.InternalExtensions.IsInMemoryQueryContext method can't get replaced query compiler.

[IsInMemoryQueryContext source code](https://github.com/zzzprojects/EntityFramework-Plus/blob/29acd6b1eea9191727d915bc66c384f29f43d03a/src/shared/Z.EF.Plus._Core.Shared/EFCore/IQueryable%60/IsInMemoryQueryContext.cs)

Stack trace:
NullReferenceException: Object reference not set to an instance of an object.
Z.EntityFramework.Plus.InternalExtensions.IsInMemoryQueryContext<T>(IQueryable<T> query)
Z.EntityFramework.Plus.QueryFutureExtensions.Future<T>(IQueryable<T> query)

Startup.cs:
```
services.AddDbContextPool<Context>(options =>
{
    options.UseSqlServer(_connectionString);
    options.ReplaceService<IQueryCompiler, CustomQueryCompiler>();
});
```

Query:
var test = ctx.Posts.Future();

EF core version 2.1

**Comment by JonathanMagnan** [comment]
Hello @vsopko ,

Do you think you could provide a project sample with this issue?

It will help my developer investigate the issue more efficiently.

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by vsopko** [comment]
@JonathanMagnan
Sorry, i can't find any time to extract and simplify code for this issue from our repository.
To reproduce it you just need to:
1. Add empty class CustomQueryCompiler.cs
```
using Microsoft.EntityFrameworkCore.Query.Internal;
public class CustomQueryCompiler: QueryCompiler
{}
```
2. Add ReplaceService<IQueryCompiler, CustomQueryCompiler>(); to db context initialization in Startup.cs
