### ISSUE TITLE
Audit: DataContext.Configuration.AutoDetectChangesEnabled=false，audit failed.

### ISSUE THREAD

**Issue by codeex** [zzzprojects/EntityFramework-Plus#438]
first: Audit: DataContext.Configuration.AutoDetectChangesEnabled=false;
If the entities of commited has child table and child table hasn't primary key,EF6 SaveChanges() success,
but SaveChanges(audit) failed.
why solved this question?

**Comment by JonathanMagnan** [comment]
Hello @codeex ,

Do you think you could provide a project sample with this issue?

It will help my developer investigate the issue more efficiently.

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @codeex ,

This issue will be closed since we haven't heard back from you.

We will be happy to re-open it as soon as you provide more information.

Best Regards,

Jonathan
