### ISSUE TITLE
How to implement in CTOR

### ISSUE THREAD

**Issue by ljfolino** [zzzprojects/EntityFramework-Plus#45]
I would like to initialize the filter in the constructor of my DbContext, but I do not see any examples of doing this.  I have tried passing this to the QueryFilterManager.InitilizeGlobalFilter function, but it does not seem to do anything.  Now I am using a somewhat complex scenario using an autogenerator set of pocos and an interface to create the filter, but I would think it should work.  Any ideas or a simple example of how to implement in a constructor?

**Comment by zzzprojects** [comment]
Since version 1.4.x for EF6 (The major revamp for Query Filter feature)

Global filter are now global, you don't need anymore to use FilterWithContextContext.InitilizeGlobalFilter 

I'm not sure to understand correctly the question, you want to initialize filter in the constructor of the DbContext?

```csharp
public class FilterWithContextContext : DbContext
{
    public FilterWithContextContext() : base("CodeFirstEntities")
    {
        LoadFilter();
    }

    public void LoadFilter()
    {
        this.Filter<FilterWithContext_Entity>(x => x.Where(y => y.ColumnInt < 100));
    }

    public DbSet<FilterWithContext_Entity> FilterWithContext_Entities { get; set; }
}

     
public class FilterWithContext_Entity
{
    public int Id { get; set; }
    public int ColumnInt { get; set; }
}
```

I'm probably missing something here since the answer seem to easy so I will wait until you provide me more detail ;)

**Comment by ljfolino** [comment]
I over complicated what needed to be done.  This was caused because I was trying to implement it in an interface to work with a T4 template to auto-generate my Entities.  I thought it was this simple, but wasn't sure since there wasn't an example.
