### ISSUE TITLE
IncludeFilter returns empty list

### ISSUE THREAD

**Issue by Rainson12** [zzzprojects/EntityFramework-Plus#450]
When using EF+ with EF 6.1.3 / MySql.Data 6.10.7.0 the Include Filter doesnt work.
`db.Employees.Where(x => x.Lastname == "Doe").IncludeFilter(x => x.TimeRegistrations).ToList();`

returns a single employee object with employees[0].TimeRegistrations.Count is equal to 0 while

`db.Employees.Where(x => x.Lastname == "Doe").Include(x => x.TimeRegistrations).ToList();`
returns a single employee with employees[0].TimeRegistrations.Count is equal to 1

Im using EF+ 1.8.21 for .Net Framework 4.5.2

**Comment by JonathanMagnan** [comment]
Hello @Rainson12 ,

Do you think you could provide a project sample with this issue?

It will help my developer investigate the issue more efficiently.

You can also write one online, here is an example to get you started: https://dotnetfiddle.net/WdiJTj

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by Rainson12** [comment]
Hey @JonathanMagnan 
A sample wouldnt help you as you would need to install the Mysql .Net Connector..

**Comment by Rainson12** [comment]
Another issue is that:
`var employee = db.Employees.Where(x => true).Include(x => x.TimeRegistrations).IncludeOptimized(x => x.Absences.Where(y => y.From > from)).ToList();` -> works

`var employee = db.Employees.Include(x => x.TimeRegistrations).IncludeOptimized(x => x.Absences.Where(y => y.From > from)).ToList(); `-> doesnt work ->
`'Die auf Typ "System.Data.Entity.Core.Objects.ObjectQuery`1[TimeRegistrationCheckUsers.Data.Employees]" deklarierte Methode "System.Data.Entity.Core.Objects.ObjectQuery`1[TimeRegistrationCheckUsers.Data.Employees] IncludeSpan(System.Data.Entity.Core.Objects.Span)" kann nicht mit einer Instanz vom Typ "System.Linq.IOrderedQueryable`1[TimeRegistrationCheckUsers.Data.Employees]" aufgerufen werden.'`

Eng:
`method 'System.Data.Entity.Core.Objects.ObjectQuery`1[TimeRegistrationCheckUsers.Data.Employees] IncludeSpan(System.Data.Entity.Core.Objects.Span)' declared on type 'System.Data.Entity.Core.Objects.ObjectQuery`1[TimeRegistrationCheckUsers.Data.Employees]' cannot be called with instance of type 'System.Linq.IOrderedQueryable`1[TimeRegistrationCheckUsers.Data.Employees]'`
