### ISSUE TITLE
why the BulkUpdate operation generate sql strange with select  sql first and inner join sql second

### ISSUE THREAD

**Issue by nlh774** [zzzprojects/EntityFramework-Plus#452]
I'm using mysql 5.7.23,EntityFramework-Plus,EF6

using (EFContext context = new EFContext())
            {
                context.Database.Log = (message) =>   //vs~output sql
                {
                    Debugger.Log(0, "Sql", message);
                };
                int x = context.TestEF.Where(t => t.Id == 1).Update(t => new TestEFContract { Name = "nlh", UpdatedOn = DateTime.Now });
                return Json("", JsonRequestBehavior.AllowGet);
            }

generate sql:
①
SELECT
`Extent1`.`Id`,
`Extent1`.`Name`,
`Extent1`.`Sex`,
`Extent1`.`CreatedOn`,
`Extent1`.`CreatedBy`,
`Extent1`.`UpdatedOn`,
`Extent1`.`UpdatedBy`,
`Extent1`.`IsDel`,
`Extent1`.`Remark`
FROM `TestEF` AS `Extent1`
 WHERE 1 = `Extent1`.`Id` 
② 
UPDATE `TestEF` AS A
INNER JOIN ( SELECT
`Extent1`.`Id`,
`Extent1`.`Name`,
`Extent1`.`Sex`,
`Extent1`.`CreatedOn`,
`Extent1`.`CreatedBy`,
`Extent1`.`UpdatedOn`,
`Extent1`.`UpdatedBy`,
`Extent1`.`IsDel`,
`Extent1`.`Remark`
FROM `TestEF` AS `Extent1`
 WHERE 1 = `Extent1`.`Id`
           ) AS B ON A.`Id` = B.`Id`
SET A.`Name` = @zzz_BatchUpdate_0,
A.`UpdatedOn` = @zzz_BatchUpdate_1
-- @zzz_BatchUpdate_0: 'nlh' (Type = String, IsNullable = false, Size = 3)
-- @zzz_BatchUpdate_1: '2019/1/28 9:55:50' (Type = DateTime, IsNullable = false)

my question：
①why the BulkUpdate generate the select sql first , not update directly?
②why the BulkUpdate generate the sql  with inner join ,not directly as
UPDATE `TestEF` AS A
WHERE 1 = `A`.`Id`
SET A.`Name` = @zzz_BatchUpdate_0
it is also refer to https://github.com/zzzprojects/EntityFramework-Plus/issues/349

**Comment by JonathanMagnan** [comment]
Hello @nlh774 ,

> why the BulkUpdate generate the select sql first , not update directly?

The first `SELECT` is not executed. We only generate it and we need to call some Interceptor when generating it which log it.

> why the BulkUpdate generate the sql with inner join ,not directly as

Because for some scenario, your `UPDATE` will not work. We will eventually optimize it to perform directly an `UPDATE` whenever we can and use the `JOIN` when necessary but since it's complex, we currently have no short term plan to optimize it.

Let me know if that answer to your both questions.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
