### ISSUE TITLE
Explicitly resolve futures

### ISSUE THREAD

**Issue by Swoorup** [zzzprojects/EntityFramework-Plus#456]
Is there a reason, why decision was made to not resolve futures by not specifying explicitly, i.e instead of the first invocation of materializing(`ToList` or `AsEnumerable`), it could have something like: 

```CSharp
var postsFut = ctx.Posts.Future();
var ordersFut = ctx.Orders.Future();

ctx.Resolve(posts,orders);
// All future resolved explicitly at this point

var posts = postsFut.ToList();
var orders = ordersFut.ToList();
```

What happens in case of multiple threads using the same context as of now?

**Comment by JonathanMagnan** [comment]
Hello @Swoorup ,

The reason is to make it works like Future in `NHibernate`. 

Honestly, I prefer implicit execute but there is already a method if you want to explicitly call it.

```csharp
QueryFutureManager.ExecuteBatch(ctx);
```

or

```csharp
ordersFut.GetResultDirectly();
```

## Multi-Threads

> What happens in case of multiple threads using the same context as of now?

`Entity Framework` is not really thread friendly. You cannot perform `CRUD` operation in a context shared in multiple thread. It will eventually lead you to some side impact with the `Change Tracker`. So using `Future` in a multi-thread context will result to concurrency error but you will get some error as well without `Future.

Let me know if that answer correctly to all your questions.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by Swoorup** [comment]
That's fair enough and understandable. 👍
