### ISSUE TITLE
Default cache policy & absolute expiration

### ISSUE THREAD

**Issue by sakopov** [zzzprojects/EntityFramework-Plus#48]
Not sure i'm completely following how this works, but if i set up my default cache policy as follows (using memory cache) in the app start-up events:

```
            var options = new CacheItemPolicy()
            {
                AbsoluteExpiration = DateTimeOffset.Now.AddMinutes(5)
            };

            QueryCacheManager.DefaultCacheItemPolicy = options;
```

EF will only cache objects for the first 5 minutes after app pool's initial start-up. After 5 minutes all objects will be inserted as expired. At least this is the behavior i'm seeing. Is there a way to configure default cache policy so that it is calculating absolute expiration from the time of cache insertion and not from the time the `CacheItemPolicy` instance is created.

**Comment by zzzprojects** [comment]
Hello @sakopov ,

As you noticed, the AbsoluteExpiraton is an absolute DateTime so that will not work.

Something which may look closer to your requirement is using [SlidingExpiration](https://msdn.microsoft.com/en-us/library/system.runtime.caching.cacheitempolicy.slidingexpiration(v=vs.110).aspx). The cache item will be evicted if not accessed in the last 5 minutes.

However, that will not fully fill your requirement either since you probably want to evict the cache item after five minutes even if the item has been accessed.

We will instead implement a DefaultCacheItemPolicyFactory feature

```csharp
QueryCacheManager.DefaultCacheItemPolicyFactory = 
   () => new CacheItemPolicy() { AbsoluteExpiration = DateTimeOffset.Now.AddMinutes(5) };
```

Since the CacheItemPolicy is created in a lambda expression, using this property will allow setting an AbsoluteExpire from the time the cache entry is added instead of the time from the app pool start-up.

I will try to add this feature for next week, meanwhile using SlidingExpiration may be a "good" alternative.

**Comment by sakopov** [comment]
Right on! A factory would be great for this. I can definitely use sliding expiration, however, it wouldn't be an ideal candidate for a portion of my queries. I can always do absolute expiration directly in `FromCache` so it's not a terrible setback. Thanks for the prompt response!

**Comment by zzzprojects** [comment]
The issue has been fixed.

The fix should be available for Monday

**Comment by zzzprojects** [comment]
Hello @sakopov 

The CacheItemPolicyFactory has been added in v1.4.4

```csharp
QueryCacheManager.CacheItemPolicyFactory = 
   () => new CacheItemPolicy() { AbsoluteExpiration = DateTimeOffset.Now.AddMinutes(5) };
```

Let me know if that's working.

Best Regards,

Jonathan

**Comment by zzzprojects** [comment]
Closing: Issue Fixed
