### ISSUE TITLE
Cannot set MySqlCommand.CommandText when there is an open DataReader for this command; it must be closed first.

### ISSUE THREAD

**Issue by yedajiang44** [zzzprojects/EntityFramework-Plus#492]
code
```csharp
        public async Task<PagedResult<EmployeRegisterRespone>> Search(EmployeRegisterFilter filter)
        {
            context.Filter<Staffinfo>(list => list.Where( x => x.Sex == (int)filter.Sex));
            var futureList = context.Staffinfo.Skip(filter.CurrentPage).Take(filter.PageSize).Future();
            var futureCount = context.Staffinfo.DeferredCount().FutureValue();

            return new PagedResult<EmployeRegisterRespone>
            {
                List = mapper.Map<IList<EmployeRegisterRespone>>(await futureList.ToListAsync()),
                Pagination = new Pagination
                {
                    Current = filter.CurrentPage,
                    PageSize = filter.PageSize,
                    Total = futureCount.Value
                }
            };
        }
```
MySql : 5.7.24
Net Core : 2.1
Error message : `Cannot set MySqlCommand.CommandText when there is an open DataReader for this command; it must be closed first.`

**Comment by JonathanMagnan** [comment]
Hello @yedajiang44 ,

Is it possible to provide a full code or runnable solution with this issue?

It makes our job easier/faster when we already have a code that reproduces it.

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
