### ISSUE TITLE
[Preview 9] IncludeFilter

### ISSUE THREAD

**Issue by vertonghenb** [zzzprojects/EntityFramework-Plus#515]
Preview 9 is being released somewhere tomorrow (4th of september) when we can expect to have `IncludeFilter` enabled again? Pretty eager to try out this new flavory goodness 👍.

**Comment by JonathanMagnan** [comment]
Hello @vertonghenb ,

At this moment, I cannot guarantee if it will work as we didn't try it yet with the `Preview 9`. The last time, it was not working due to some issues with the `SelectMany`.

We will for sure check it tomorrow but if you wish, just let us know when the `Preview 9` will be released so we could start to work on it asap ;)

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @vertonghenb ,

We tried the latest preview today, however, some internal core stuff still has been modified/renamed.

So we will check again during the weekend

**Comment by vertonghenb** [comment]
Ok @JonathanMagnan , let me know if we can start testing!

**Comment by JonathanMagnan** [comment]
Hello @vertonghenb ,

The v3.0.9-preview9-01 has been released.

All features should work in this version including the `IncludeFilter` one ;)

Best Regards,

Jonathan

**Comment by vertonghenb** [comment]
Jonathan,

I've been playing around with it and looks great! However is there a possibility to add a ThenInclude after the filter? 
> Before
```cs
var article = await _context.Articles
    .Include(x => x.Comments).ThenInclude(x => x.Author)
    .AsNoTracking()
    .SingleOrDefaultAsync(x => x.Id == request.Id);
return article;

```

> With IncludeFilter
```cs
var article = await _context.Articles
    .IncludeFilter(x => x.Comments).ThenInclude(x => x.Author) // issue is here, how do you add this ThenInclude?
    //.AsNoTracking() Since it doesn't allow notracking.
    .SingleOrDefaultAsync(x => x.Id == request.Id);
return article;
```

**Comment by JonathanMagnan** [comment]
Hello @vertonghenb ,

At this moment, that's not possible. You need to do it like you were doing it in `EF6` (using multiple `IncludeFilter`).

We tried last month to add it. Unfortunately, time was missing to complete this request.

We will eventually support it but the effort at this moment is too high as a lot of internal code need to be modified to add the support to `ThenIncludeFilter`.

Let hope we find the time before the end of 2019 ;)

**Comment by salaros** [comment]
> The v3.0.9-preview9-01 has been released.
> All features should work in this version including the `IncludeFilter` one ;)

So the info [in the README](https://github.com/zzzprojects/EntityFramework-Plus#query-includefilter) is incorrect?
