### ISSUE TITLE
Bulk Update generating invalid query in PostgreSQL

### ISSUE THREAD

**Issue by Juulsgaard** [zzzprojects/EntityFramework-Plus#518]
### Description
When using the Update method with Postgres, the generated query isn't valid.
This occurs with simple queries without any where clauses, as well as complicated ones.
This only occurs when making relative update calls.

```c#
Context.SomeDbSet.Update( 
    x => new SomeModel{
        SomeProp= x.SomeProp + 1
    }
);
```

The generated query looks something like this:

```SQL
UPDATE "SomeModel"
SET "SomeProp" = x."SomeProp" + 1
WHERE EXISTS ( 
  SELECT 1 FROM (SELECT s."Id", s."SomeProp" FROM "SomeModel" AS s ) B
  WHERE "SomeModel"."Id" = B."Id"
)
```

Which isn't valid Postgres SQL syntax.

### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
42P01: missing FROM-clause entry for table "x"

Stack trace:
[ ] at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
[ ] --- End of stack trace from previous location where exception was thrown ---
[ ] at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 1032
[ ] --- End of stack trace from previous location where exception was thrown ---
[ ] at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming) in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:line 444
[ ] at Npgsql.NpgsqlDataReader.NextResult() in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:line 332
[ ] at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1218
[ ] at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1042
[ ] at Npgsql.NpgsqlCommand.ExecuteNonQuery() in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1025
[ ] at Z.EntityFramework.Plus.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory) in C:\Users\Jonathan\Desktop\Z\TFS\EFPlus\Z.EntityFramework.Plus\shared\Z.EF.Plus.BatchUpdate.Shared\BatchUpdate.cs:line 407

```

### Further technical details
.NET CORE 2.2
- *EF version:* EF Core 2.2.6
- *EF Plus version:* Core 2.0.7
- *Database Provider:* PostgreSQL 9.6.14

**Comment by JonathanMagnan** [comment]
Hello @Juulsgaard ,

Unfortunately for PostgreSQL provider, the support to update using the current column value is not yet supported ;(

It works in many other providers such as SQL Server since we can make a join in the update, but PostgreSQL doesn't support this kind of syntax

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
