### ISSUE TITLE
How to filter related entities with DBSetFilter?

### ISSUE THREAD

**Issue by yoazerty** [zzzprojects/EntityFramework-Plus#527]
### Description
Hello,

We are implementing a multi-tenant application with DBSetFilter. This works very well if we only query the filtered table. Is there a way to also filter sub tables?

For example 
Customers are affected to an entity and their invoices are also linked to this entity.
If I try to get the filtered customers for the entity it is working
If I try to get the filtered invoices linked to this entity, it is working
BUT if I try to get all the invoices of the customer and I just want the one linked to the entity, it is not working :

db.customers.FirstOrDefault().Invoices : I get all the invoices and i just want the one of the selected entity

Is there a way to global filter them with the DBSetFilter?

Thank you

**Comment by JonathanMagnan** [comment]
Hello @yoazerty ,

Unfortunately no, we already tried an attempt with https://entityframework-plus.net/query-filter, but we never successfully make it 100% work with the `Interceptor` strategy we used.

The `Query DbSetFilter` is the old `Query Filter` feature code before we moved to the `Interceptor` strategy.

Here are some alternative solutions:

- You can try with the library: https://entityframework-dynamicfilters.net/
- You can do it with EF Classic: https://entityframework-classic.net/query-filter (Be careful, this library is a whole replacement to EF 6... since we can change the core code, that features easily work under  it)

Let me know if that answer to your question

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by yoazerty** [comment]
Hello,

Thank you for your quick reply :-)
Unfortunately we are too closed our release date and to be honest, I do fear a little bit to use a Framework which replaces totally EntityFramework, unknowing the potential impacts (in terms of reliability and the effort to migrate).
So we are going to keep using the DbSetFilter and pay attention to our linked tables queries.

I will keep an eye to EF Classic Query filter but at a first glance, I did not see how to deal with that problem.

Best regards,
yoazerty.

**Comment by JonathanMagnan** [comment]
Hello @yoazerty ,

That's understandable and the right decision to take on your side ;)

With EF Classic, you only need to set a filter on the `Customer` and one on `Invoice`. When retrieving related invoice, they will be automatically filtered by default (if I understand correctly your request).

Can we close this request? We will re-open whenever you will have more time to work on it?

**Comment by yoazerty** [comment]
Yes you can close it, thank you very much for your support.

Best regards,
Yoazerty

Le mer. 2 oct. 2019 à 14:04, Jonathan Magnan <notifications@github.com> a
écrit :
