### ISSUE TITLE
UpdateFromQuery<> generates unnecessary INNER JOIN

### ISSUE THREAD

**Issue by cgonzalezri** [zzzprojects/EntityFramework-Plus#531]
### Description
I was testing EF Plus and got some weird SQL updates statements.

```
context.Unidad_Medida
    .Where(a => a.Codigo == 1448)
    .UpdateFromQuery(a => new Unidad_Medida()
    {
          Denominacion = "test"
    });
```

I thought that the code generated will be something like

`UPDATE Unidad_Medida SET Denominacion = 'test' WHERE Codigo = 1448`

Instead, I got

```
exec sp_executesql N'
UPDATE A 
SET A.[Denominacion] = @zzz_BatchUpdate_0
FROM [dbo].[Unidad_Medida] AS A
INNER JOIN ( SELECT [u].[Codigo], [u].[Calidad_Registro_Uso], [u].[Denominacion], [u].[SAP_Clave]
FROM [dbo].[Unidad_Medida] AS [u]
WHERE [u].[Codigo] = 1448
           ) AS B ON A.[Codigo] = B.[Codigo]
',N'@zzz_BatchUpdate_0 nvarchar(6)',@zzz_BatchUpdate_0=N'prueba'
```

Why I got that INNER JOIN thats makes the query significant slower?

### Further technical details
- EF version: 3.0.0
- EF Plus version: 3.0.13
- Database Provider: SQL Server

**Comment by JonathanMagnan** [comment]
Hello @cgonzalezri ,

It happens because we took the easy road.

This part is generated by Entity Framework:

```sql
SELECT [u].[Codigo], [u].[Calidad_Registro_Uso], [u].[Denominacion], [u].[SAP_Clave]
FROM [dbo].[Unidad_Medida] AS [u]
WHERE [u].[Codigo] = 1448
```

So one quick way to support a feature like this one is to use the `SELECT` as a derived table and make a join. Some updates could not work directly like the way you did since some `INNER JOIN` are required since the query is very complex, so we took the road that `FIT` all those scenarios.

Soon or later, we will need to take some time on our side to improve this feature. As some statement could be improved as you have shown but unfortunately, as a free library, it hard for ourselves to take enough time to make it happens ;(

Let me know if that answers correctly to this question.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by cgonzalezri** [comment]
Hello @JonathanMagnan ,

Yeah, your answer is totally correct. The Update function from EF Extensions works the same way?

Thank you very much for your work!

**Comment by JonathanMagnan** [comment]
There is some slight difference (It uses a MERGE statement for most scenario) but both will eventually work the same way.
