### ISSUE TITLE
Not Compatible with netCore 2.2 on latest version

### ISSUE THREAD

**Issue by IainCoSource** [zzzprojects/EntityFramework-Plus#539]
### Description
Severity	Description	Project	File	Line	Suppression State
Error	Package Z.EntityFramework.Plus.EFCore 3.0.13 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Package Z.EntityFramework.Plus.EFCore 3.0.13 supports: netstandard2.1 (.NETStandard,Version=v2.1)	VetShop.Services	\Services\Services.csproj	1	

### Exception
Severity	Description	Project	File	Line	Suppression State
Error	Package Z.EntityFramework.Plus.EFCore 3.0.13 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Package Z.EntityFramework.Plus.EFCore 3.0.13 supports: netstandard2.1 (.NETStandard,Version=v2.1)	Services	Services\Services.csproj	1	
e).

```
Exception message:
Stack trace:
```

### Fiddle or Project
Create a Fiddle that reproduce the issue: https://dotnetfiddle.net/zB4SGA

Or provide a project/solution that we can run to reproduce the issue.
- Make sure the project compile
- Make sure to provide only the code that is required to reproduce the issue, not the whole project
- You can send private code here: info@zzzprojects.com

_Note: If you are not able to provide code we can run and that reproduce the issue, we will not be able to fix it either._

### Further technical details
- EF version:
- EF Plus version:
- Database Provider:

**Comment by JonathanMagnan** [comment]
Hello @IainCoSource ,

You probably use EF Core 2.x, you also need to use the v2.x of our library.

Here is the latest version: https://www.nuget.org/packages/Z.EntityFramework.Plus.EFCore/2.0.8

We are currently checking about what's the best way to handle this since a lot of people do the same thing as you (use the latest version of our library even if they don't use the latest version of EF Core)

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @IainCoSource 

Did you get the time to try the latest version?

Looking forward to hearing from you, 

Jon

**Comment by IainCoSource** [comment]
Hi,

 

Yes it is working now however the includeFilter is producing incorrect data.

 

return context.CatalogProductEntity

                .IncludeFilter(s =>

                    s.CatalogProductEntityInts.Where(a =>

                        attributeIdsWeWant.Any(b => b == a.AttributeId) && (a.StoreId == 0 || a.StoreId == _activeWebsiteInformation.Id ) ))

 

using the following code I get 5 rows instead of the 7 in answer.

 

My corresponding sql query to get answer.csv is 

SELECT * FROM  catalog_product_entity_int

where entity_id =3970 and (store_id =3 or store_id =0) and attribute_id in (97,99,115,148,155,156,157,73,76,84,86,87,88,89,109,110,111,133,147,149,150,151,152,153,154,75,85,77,82);

 

Note this is running EFCore2.2 against Mysql

Iain Rough


AMR Office Park, 3 Concorde E Rd, Johannesburg, 2008

     <https://i.ibb.co/x6rT9N1/tell.png>     <tel:1300%20736%20002> 010 007 5286
     <https://i.ibb.co/C7Rzhp4/skype.png>   iain-cosource 
     <https://i.ibb.co/LpNjcHH/whatsapp.png>    <tel:1300%20736%20002> 010 007 5286
     <https://i.ibb.co/6n1j88L/web.png>    <http://www.cosource.net.za/> http://www.cosource.net.za/

**Comment by JonathanMagnan** [comment]
Hello @IainCoSource ,

We tried on our side and everything works as expected.

It is possible to provide a runnable project that shows this error? Or at least provide the query generated by our library so we could try to understand what's happening.

**Comment by IainCoSource** [comment]
Issue was on my side 

 

Iain Rough


AMR Office Park, 3 Concorde E Rd, Johannesburg, 2008

     <https://i.ibb.co/x6rT9N1/tell.png>     <tel:1300%20736%20002> 010 007 5286
     <https://i.ibb.co/C7Rzhp4/skype.png>   iain-cosource 
     <https://i.ibb.co/LpNjcHH/whatsapp.png>    <tel:1300%20736%20002> 010 007 5286
     <https://i.ibb.co/6n1j88L/web.png>    <http://www.cosource.net.za/> http://www.cosource.net.za/
