### ISSUE TITLE
Npgsql column add not support?

### ISSUE THREAD

**Issue by tanghaojie** [zzzprojects/EntityFramework-Plus#540]
### Description
I use ef6 and npgsql , i want to execute like this:
```SQL
update "admin"."Application" set "Order" = "Order" + 1
```
my code is:
```C#
query.Update(x => new Entities.EF.Application { Order = x.Order + 1 });
```
it will generate this sql:
```SQL
UPDATE "admin"."Application"
SET "Order" =  B."Order" + 1  
AS
"C1" 
WHERE EXISTS ( 
	SELECT 1 FROM (
		SELECT 
		"Extent1"."Id", 
		"Extent1"."Name",
		"Extent1"."Remark", 
		"Extent1"."Url", 
		"Extent1"."Ip", 
		"Extent1"."Port",
		"Extent1"."Location",
		"Extent1"."Author", 
		"Extent1"."Manager", 
		"Extent1"."Owner", 
		"Extent1"."Data", 
		"Extent1"."CreationTime", 
		"Extent1"."Order" 
		FROM "admin"."Application" AS "Extent1") B
               WHERE "admin"."Application"."Id" = B."Id"
```
not valid in postgrsql

**Comment by JonathanMagnan** [comment]
Hello @tanghaojie ,

Unfortunately, this kind of update is not supported for PostgreSQL (due to how we generate the query).

It works under some other providers such as SQL Server but no PostgreSQL.

We already tried to make it works, but we failed.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by tanghaojie** [comment]
> Hello @tanghaojie ,
> 
> Unfortunately, this kind of update is not supported for PostgreSQL (due to how we generate the query).
> 
> It works under some other providers such as SQL Server but no PostgreSQL.
> 
> We already tried to make it works, but we failed.
> 
> Best Regards,
> 
> Jonathan
> 
> **Performance Libraries**
> `context.BulkInsert(list, options => options.BatchSize = 1000); `
> [Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) • [Dapper Plus](http://dapper-plus.net/)
> 
> **Runtime Evaluation**
> `Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
> [C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

thanks for you reply
