### ISSUE TITLE
Is it always server evaluation ?

### ISSUE THREAD

**Issue by moataz1991** [zzzprojects/EntityFramework-Plus#544]
Hello..
I have a question ..
no matter how query is complicated using your awesome library, is it always server-evaluated ?
or sometimes it do client evaluation ? <-- if any , how to avoid client evaluation

Thanks :)

**Comment by JonathanMagnan** [comment]
Hello @moataz1991,

I believe we are missing some important pieces of information to answer correctly such as which features you are speaking on?

For example, client evaluation might be sometime very good with caching. But usually you want to try to avoid client evaluation but that's not always true.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by mRmEEeZ** [comment]
consider having this query...
```
...
.IncludeFilter(parent=>parent.children.Where(child=>child.ToString().Contains("name",StringComparer.InvariantCultureIgnoreCase))
.Where(parent => parent.Id > 10)
.OrderBy(...)
.Skip(10)
.Take(10)
.ToList();
```

simply getting complex objects with C#-complex where clause
is it still server-evaluated?

**Comment by JonathanMagnan** [comment]
For the `IncludeFilter` feature, our library uses anonymous type +  `Entity Framework` to execute queries. We don't generate the SQL statement or choose how it's executed.

So I cannot say if this one will be server-evaluated or not.  We don't control anything here.

So best guess on your side is to try it and monitor what happens in the database (and disable client-side evaluation anyway because most of the time, that's very bad behavior)
