### ISSUE TITLE
NullReferenceException When using Any Z.EntityFramework.Plus Method?

### ISSUE THREAD

**Issue by Josrph** [zzzprojects/EntityFramework-Plus#547]
### Description
whenever i use an extension method from Z.EntityFramework.Plus namespace i get a NullReferenceException.
### Exception
Exception thrown: 'System.NullReferenceException' in Z.EntityFramework.Plus.EF6.dll
System.Transactions Critical: 0 : <TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Unhandled exception</Description><AppDomain>MyApp.exe</AppDomain><Exception><ExceptionType>System.NullReferenceException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>Object reference not set to an instance of an object.</Message><StackTrace>   at Z.EntityFramework.Plus.BatchDelete.Execute[T](IQueryable`1 query)
   at Z.EntityFramework.Plus.BatchDeleteExtensions.Delete[T](IQueryable`1 query, Action`1 batchDeleteBuilder)
   at Z.EntityFramework.Plus.BatchDeleteExtensions.Delete[T](IQueryable`1 query)
   at MyApp.Program.Main() in C:\Users\Joseph\source\repos\MyApp\MyApp\Program.cs:line 23</StackTrace><ExceptionString>System.NullReferenceException: Object reference not set to an instance of an object.
   at Z.EntityFramework.Plus.BatchDelete.Execute[T](IQueryable`1 query)
   at Z.EntityFramework.Plus.BatchDeleteExtensions.Delete[T](IQueryable`1 query, Action`1 batchDeleteBuilder)
   at Z.EntityFramework.Plus.BatchDeleteExtensions.Delete[T](IQueryable`1 query)
   at MyApp.Program.Main() in C:\Users\Joseph\source\repos\MyApp\MyApp\Program.cs:line 23</ExceptionString></Exception></TraceRecord>
An unhandled exception of type 'System.NullReferenceException' occurred in Z.EntityFramework.Plus.EF6.dll
Object reference not set to an instance of an object.

### Further technical details
nuget packages currently installed:

EntityFramework 6.3

MySql.Data 8.0.18
MySql.Data.EntityFramework 8.0.18

Z.EntityFramework.Plus.EF6 1.12.3

i really wanna use the library but i can't because of this.

**Comment by JonathanMagnan** [comment]
Hello @Josrph ,

Do you think you could provide a project sample with this issue?

It will help my developer investigate the issue more efficiently.

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by Josrph** [comment]
OK, i found the source of the problem which was just a simple foreign key constraint!

when i installed the library i was in a hurry and the first thing i did to see if it works or not was trying to  delete a related parent entity without deleting the child entities first and i got a NullReferenceException for that.

but now, while this question is answered another one pops up which is why the misleading NullReferenceException is being raised while in fact it was just a foreign key constraint not being met.

a foreign key constraint exception should've been raised rather.

i leave that to the entity-framework-plus team to investigate further.

mean while big thanks to @JonathanMagnan for the instrest.

**Comment by JonathanMagnan** [comment]
Hello @Josrph ,

I'm happy you got it fixed.

As said, we will be happy to fix/change the error message it if you could provide a project. Otherwise, I don't think anything will be done here.
