### ISSUE TITLE
Mixing Where and OrderBy calls

### ISSUE THREAD

**Issue by Ar4ics** [zzzprojects/EntityFramework-Plus#549]
### Description
When I am mixing Where and OrderBy calls, I am getting exception:
### Exception

```
Exception has occurred: CLR/System.ArgumentException
Необработанное исключение типа "System.ArgumentException" в System.Private.CoreLib.dll: 'Expression of type 'System.Linq.IOrderedQueryable`1[AspNetCoreBustronic.Models.RouteSegments]' cannot be used for return type 'System.Linq.IOrderedEnumerable`1[AspNetCoreBustronic.Models.RouteSegments]''
```

### Code
``
<pre>
var routes = context.Routes
.Where(e => e.IsReady.HasValue && e.IsReady.Value == true && !e.DeletedAt.HasValue)
.IncludeFilter(e => e.RouteSegments.Where(e => !e.DeletedAt.HasValue).OrderBy(e => e.Position))
.ToList();
</pre>
``
### Further technical details
- EF version: 3.0 core latest
- EF Plus version: latest
- Database Provider: Npgsql latest

**Comment by JonathanMagnan** [comment]
Hello @Jon,

Do you think you could provide a project sample with this issue?

It will help my developer investigate the issue more efficiently.

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @Ar4ics 

Since our last conversation, we haven't heard from you. 

Don't hesitate to provide a project sample with the issue.

looking forward to hearing from you, 

Jon

**Comment by JonathanMagnan** [comment]
Hello @Ar4ics 
A quick reminder that we are here to assist you. 

Feel free to send us a project sample with the issue, so that we can help you solve it! 

Best regards, 

Jon
