### ISSUE TITLE
String interpolation problem

### ISSUE THREAD

**Issue by API-kernel** [zzzprojects/EntityFramework-Plus#554]
I have a problem with this code:

        public static void Main()
        {
            var now = DateTime.Now;
            
            Test(e => new Access
            {
                Comment = $"{now}" + "test" 
            });
            //OK: e => new Access() {Comment = (Format("{0}", Convert(value(Program+<>c__DisplayClass0_0).now)) + "test")}

            Test(e => new Access
            {
                Comment = now + " " + e.AccessId 
            });
            //OK: e => new Access() {Comment = ((Convert(value(Program+<>c__DisplayClass0_0).now) + " ") + Convert(e.AccessId))}
            
            Test(e => new Access
            {
                Comment = $"{now} {e.AccessId}" 
            });
            /*
              ERROR: e => new Access() {Comment = Format("{0} {1}", Convert(value(Program+<>c__DisplayClass0_0).now), Convert(e.AccessId))} 
              System.Exception: Oops! The current query contains a client-side evaluation. The query must contain an expression that can be converted on server-side (into a SQL).
              в Z.EntityFramework.Plus.InternalExtensions.CreateCommand(IQueryable source, RelationalQueryContext& queryContext)
              в Z.EntityFramework.Plus.BatchUpdate.GetInnerValues[T](IQueryable`1 query, Expression`1 updateFactory, IEntityType entity)
              в Z.EntityFramework.Plus.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
            */

            
            Test(e => new Access
            {
                Comment = $"{now}" + e.AccessId 
            });
            /*
              ERROR: e => new Access() {Comment = (Format("{0}", Convert(value(Program+<>c__DisplayClass0_0).now)) + Convert(e.AccessId))}
              System.Data.SqlClient.SqlException (0x80131904): Must declare the scalar variable "@__Format_0"
              Incorrect syntax near the keyword 'AS'.
              в System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
              в System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
              в System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
              в System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
              в System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
              в System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
              в Z.EntityFramework.Plus.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
            */

        }

        private static void Test(Expression<Func<Access, Access>> updateFactory)
        {
            using (var context = new EntityContext())
            {    
                try
                {
                    context.Access
                        .Where(e => e.AccessId == 1)
                        .Update(updateFactory);
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"ERROR: {updateFactory}");
                    Console.WriteLine(ex);
                    return;
                }
                
                Console.WriteLine($"OK: {updateFactory}");          
            }
        }

### Further technical details
Z.EntityFramework.Extensions.EFCore version="2.7.20"
Z.EntityFramework.Plus.EFCore" version="2.0.24"
Z.Expressions.Eval" version="3.0.7"
Microsoft.EntityFrameworkCore" version="2.2.6"
Database Provider: MSSQL
.NET 4.8

**Comment by JonathanMagnan** [comment]
Hello @API-kernel ,

Thank you for reporting.

For the first one, there is nothing we can do since there is a client-side evaluation that we cannot support.

For the second expression, we will look at it.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @API-kernel ,

The issue has been fixed in the v3.0.27

However, we only successfully fixed it in EF Core 3.x

At this moment, we have no solution for EF Core 2.x and since the query is generated very differently (some client-side evaluation maybe?), I do not think we will be able to support it in this version.

I know that's as simple but it's possible for you to upgrade to EF Core 3.1 which also supports .NET Standard 2.0?
