### ISSUE TITLE
Audit not working

### ISSUE THREAD

**Issue by Razvan-Rosa** [zzzprojects/EntityFramework-Plus#569]
Do you have any sugestions on saving the audit.
Audit is not saving data in the database.
I am using  z.entityframework.extensions.efcore (2.6.11)
And Postgress 11.3

Exception thrown in the output when new Z.EntityFramework.Plus.Audit is called: 'System.NullReferenceException' in Z.EntityFramework.Plus.Audit.EFCore.dll
Code is:

```csharp
            using (var dbContext = _dbContextFactory.GetContext())
            {
                var existingUser = dbContext.Users.FirstOrDefault(c => c.Id == user.Id);

                existingUser.Name = user.Name;
                existingUser.Email = user.Email;

                dbContext.Users.Update(existingUser);

                Z.EntityFramework.Plus.Audit audit = new Z.EntityFramework.Plus.Audit
                {
                    CreatedBy = "ZZZ Projects" // Optional
                };
                dbContext.SaveChanges(audit);

                return dbContext.SaveChanges();
            }
```

**Comment by JonathanMagnan** [comment]
Hello @Razvan-Rosa ,

Do you think you could provide a project sample with this issue?

It will help my developer investigate the issue more efficiently. I believe your current issue might be you are missing the `AutoSavePreAction` part, but I might be wrong: https://entityframework-plus.net/ef6-audit-autosave

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by Razvan-Rosa** [comment]
Thanks @JonathanMagnan 
I was missing the AutoSavePreAction part.
