### ISSUE TITLE
Receiving "The provider for the source IQueryable doesn't implement IAsyncQueryProvider" when using IncludeOptimized().

### ISSUE THREAD

**Issue by TylerDM** [zzzprojects/EntityFramework-Plus#572]
Attempting to execute a query with an asynchronous method like `FirstOrDefaultAsync()` or `ToListAsync()` seems to be broken.  For example:
```csharp
var claims = await _dbContext.Claims.IncludeOptimized(x => x.Fees).ToListAsync();
```
Produces the error:
> System.InvalidOperationException: 'The provider for the source IQueryable doesn't implement IAsyncQueryProvider. Only providers that implement IAsyncQueryProvider can be used for Entity Framework asynchronous operations.'

**Comment by JonathanMagnan** [comment]
Hello @TylerDM ,

Do you think you could provide a project sample with this issue?

In this case, it could be in EF6, EF Core 2.x, EF Core 3.x... and we also have some async unit test, so we are not sure where to start the investigation.

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by TylerDM** [comment]
[EFPlusRepro.zip](https://github.com/zzzprojects/EntityFramework-Plus/files/4093001/EFPlusRepro.zip)

Here's a tiny project which reproduces the problem.

**Comment by JonathanMagnan** [comment]
Awesome,

The issue has been assigned to my developer. He will probably be able to look at it at the end of the week.

**Comment by JonathanMagnan** [comment]
Hello @TylerDM ,

The latest version for .NET Core 3.x should contain this fix.

Let us know if everything works as expected.

Best Regards,

Jon

**Comment by TylerDM** [comment]
I'm not receiving any errors.  I'll check more in detail later but given the nature of the issue it's likely resolved.  Thank you.

**Comment by mgraf1** [comment]
I think this issue should be re-opened. The exact same error occurs on 3.0.35 when using `FirstOrDefaultAsync` instead of `ToListAsync`

[EFPlusRepro.zip](https://github.com/zzzprojects/EntityFramework-Plus/files/4155600/EFPlusRepro.zip)

**Comment by JonathanMagnan** [comment]
Hello @mgraf1 ,

The latest version should have it fixed.

If you still have the issue, please let us know.

Best Regards,

Jon

**Comment by Frixs** [comment]
The same issue happened to me while trying to test my method containing `AnyAsync()` method.
Microsoft.EntityFrameworkCore.InMemory, version: 8.0.8

**Comment by JonathanMagnan** [comment]
Hello @Frixs ,

After looking at it, we didn't succeed in reproducing this.

Do you think you could create a runnable project with the issue? It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue. You can send it in private here info@zzzprojects.com

Best Regards,

Jon
