### ISSUE TITLE
'The instance of entity type cannot be tracked' on version > 3.0.30

### ISSUE THREAD

**Issue by gercobrandwijk** [zzzprojects/EntityFramework-Plus#581]
### Description
When updating to a version higher than 3.0.30 (version 3.0.30 is the last version on which it works good), I get an exception about already tracked entities, when using the BatchUpdateExtensions.UpdateAsync call.

The issue is occuring in my unit test (in memory EF Core database). The whole unit test is using one UnitOfWork / Database context. After some saving/mutation of the data, I do a UpdateAsync on a queryable, which includes an entity that is already in the DbContext ChangeTracker. It looks like that the library is adding the entries, that he is going to update, to the DbContext ChangeTracker. I tried to prevent this by adding AsNoTracking() to the queryable that is used by the UpdateAsync, but I still get the same error.

### Exception
Exception message: 
```
System.InvalidOperationException : The instance of entity type 'Device' cannot be tracked because another instance with the key value '{Id: 705d38c6-54fe-43b2-9610-c6448447181e}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.
```
Stack trace:
```
IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
    IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
    IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
    IdentityMap`1.Add(InternalEntityEntry entry)
    StateManager.StartTracking(InternalEntityEntry entry)
    InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
    InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey)
    EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
    EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
    EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)
    DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState)
    DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
    DbContext.Attach[TEntity](TEntity entity)
    BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
    BatchUpdateExtensions.UpdateFromQuery[T](IQueryable`1 query, Expression`1 updateFactory, Action`1 batchUpdateBuilder)
    BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory, Action`1 batchUpdateBuilder)
    <>c__DisplayClass2_0`1.<UpdateAsync>b__0()
    Task`1.InnerInvoke()
    <.cctor>b__274_0(Object obj)
    ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
    --- End of stack trace from previous location where exception was thrown ---
    ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
    Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
    --- End of stack trace from previous location where exception was thrown ---
```

### Further technical details
- EF version: EF Core 3.1.2
- EF Plus version: > 3.0.30
- Database Provider: InMemoryDatabase

**Comment by JonathanMagnan** [comment]
Hello @gercobrandwijk ,

Thank you for reporting, I will ask my developer to look at it.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @gercobrandwijk ,

My developer tried it but doesn't have any issues.

Could you provide us a runnable project with the problem? It will help my developer to investigate faster.

**Comment by JonathanMagnan** [comment]
Hello @gercobrandwijk ,

Since our last conversation, we haven't heard from you. 

don't hesitate to provide a runnable project.

best regards, 

Jon

**Comment by gercobrandwijk** [comment]
I created a project with it is reproducable. See https://github.com/gercobrandwijk/EFPlusIssue581/tree/master

In the readme you can read how to reproduce.

**Comment by JonathanMagnan** [comment]
Thank you, we successfully reproduced the issue with your project.

My developer has already an idea of what is caused this since we fixed previously a similar issue with `InMemory`. He will look at it next week.

**Comment by JonathanMagnan** [comment]
Hello @gercobrandwijk ,

We have found 2 issues in your projects.

The `InMemoryDbContextFactory`, we ask for a new whole context.

Something like this:

```csharp
 BatchUpdateManager.InMemoryDbContextFactory = () => { return new DatabaseContext(databaseContextBuilder.Options); };
```

The second error is in your GetAll, since you use the same context, it will return items that has already been loaded (even if modified in the database). So you need to use the `AsNoTracking` method:

```csharp
public List<Device> GetAllAsNoTracking(bool includeDeleted)
{
	return this.DatabaseSet
		.Where(x => includeDeleted || x.Active)
		.OrderBy(x => x.Name)
		.AsNoTracking()
		.ToList();
}
```

Let me know if that helped you.

**Comment by laurencee** [comment]
I have the same issue with an `UpdateAsync` call that's failing in a test after upgrading to 3.0.40.

Without any code changes the test succeeds on 3.0.30.

**Comment by gercobrandwijk** [comment]
@JonathanMagnan When I do what you do, it indeed works. Then the contexts are totally seperated, and than of course it cannot complain about already tracked entities in the context, because they are seperated..

But with this approach, I am not be able to execute the BatchUpdate and some other changes in the same transaction? Because it is a seperate DbContext. Do you have another approach to achieve this?

**Comment by JonathanMagnan** [comment]
Hello @gercobrandwijk ,

## Transaction

Unfortunately, I don't think that's currently possible.

However, we could simply add an options that will either to the `AsNoTracking` or not (the old behavior).

So by default, it will work like now, but by enabling that options, you will be able to use your context are you previously was doing.

## v3.0.31 changes

Just one line was modified starting of this version. When taking items to update, we take them using the `AsNoTracking` method.

This change was necessary since we learned that our `ContextFactory` with `InMemory` had a different behavior than when using a database.

The context factory copy options from the current context to the context created, but unfortunately, it cause also some side impact. The `InMemory` provider requires us to load entities to modify them, however, those entities have the same reference as entities already loaded in your application. So modifying one, automatically modify the other. So entities already loaded have the modified value.

It doesn't sound bad at all. However, for other providers like SQL Server, entities are not loaded, everything is done in the database. So entities already loaded doesn't have the modified value.

Using the `AsNoTracking` fixed this issue but created a new one for your case.

---

We will look for adding the option later this week as I'm pretty sure, that's what you would like we do ;)

**Comment by gercobrandwijk** [comment]
I do not fully understand what you are saying (most likely because I do not understand the internals of EF Core as well as you do), but it sounds very good that you are making it an option! :) Looking forward to it.

Just to understand it: You are saying that you added the AsNoTracking in version 3.0.31, which causes my issue. But AsNoTracking means (as far as I know) that EF Core will not track the entities of the following query, but how can this give the error ('The instance of entity type 'Device' cannot be tracked because another instance with the key value is already being tracked.') then? I would only expect this error could occur when you DID NOT add the AsNoTracking?

**Comment by JonathanMagnan** [comment]
Hello @gercobrandwijk ,

Sorry for the long delay,

You don't find the commit because some part of `EF Plus` is now in `EF Extensions`

A new version of `EF Extensions` has been released, we added the option `IgnoreInMemoryAsNoTracking` which will bring back the old behavior when turned to true.

For example: context.Addresses.Where(x => x.Id == 10).DeleteFromQuery(option => option.IgnoreInMemoryAsNoTracking = true);

We expect to update the EF Plus dependencies this weekend but meanwhile, you can directly update EF Extensions to get access to this option.
