### ISSUE TITLE
Could not load type 'Microsoft.EntityFrameworkCore.Query.Internal.IAsyncQueryProvider'

### ISSUE THREAD

**Issue by Tommigun1980** [zzzprojects/EntityFramework-Plus#601]
### Description
Hello,

I just updated Entity Framework and Entity Framework Plus from the latest stable versions on the  version 3 track to the latest preview packages on the version 5 track.

I now get a "System.TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Query.Internal.IAsyncQueryProvider' from assembly 'Microsoft.EntityFrameworkCore'" exception when running the following code, which worked fine prior to updating (names modified for clarity):

```c#
private readonly MemoryCacheEntryOptions MyCacheDuration = new MemoryCacheEntryOptions()
{
        AbsoluteExpirationRelativeToNow = TimeSpan.FromMinutes(5)
};

public async Task<int> GetCachedValueFromMyDbSet()
{
        return await this.myContext.MyDbSet.AsNoTracking()
                .Select(t => t.MyValue)
                .DeferredSingle().FromCacheAsync(MyCacheDuration);
}
```
### Exception
```c#
System.TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Query.Internal.IAsyncQueryProvider' from assembly 'Microsoft.EntityFrameworkCore, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Z.EntityFramework.Plus.QueryDeferred`1..ctor(IQueryable query, Expression expression)
   at Z.EntityFramework.Plus.QueryDeferredExtensions.DeferredSingle[TSource](IQueryable`1 source)
   MySources
```
### Further technical details
- EF version: 5.0.0-preview.2.20159.4
- EF Plus version: 5.0.0-preview.2.20120.8-02
- Database Provider: SQLite

**Comment by StevenHanquez** [comment]
I have the same error on my Net Core 3.1 solutions.

This code work perfectly 
```
return await Context.ActionsTables
.AsNoTracking()
.Where(act => act.Utilisateur_Id == idUtilisateur)
.ToListAsync();
```

But, if I add an "IncludeOptimized" instruction like this
```
return await Context.ActionsTables
.AsNoTracking()
.Where(act => act.Utilisateur_Id == idUtilisateur)
.IncludeOptimized(act => act.Utilisateur)
.ToListAsync();
```

I get this exception
```
System.TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Query.Internal.IAsyncQueryProvider' from assembly 'Microsoft.EntityFrameworkCore, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Z.EntityFramework.Plus.QueryIncludeOptimizedParentQueryable`1.get_Provider()
   at System.Linq.Queryable.OrderByDescending[TSource,TKey](IQueryable`1 source, Expression`1 keySelector)
```

**Further technical details**
- EF Core version: 5.0.0-preview.2.20159.4
- EF Plus Core version: 5.0.0-preview.2.20120.8-02
- Database Provider: SqlServer

**Comment by JonathanMagnan** [comment]
Hello @Tommigun1980 , @StevenHanquez ,

Thank you for reporting. It usually happens when a new version is released and some namespace has been modified in EF Core.

We will look at it and fix it.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello,

A new version has been released (which is only compatible with the latest preview version).

Could you try it and let us know if all issue has been fixed?

It was caused because the `IAsyncQueryProvider` is now under a different namespace.

Best Regards,

Jon

**Comment by StevenHanquez** [comment]
I did the update. I no longer have the error with IAsyncQueryProvider. Thank you.

**Comment by Tommigun1980** [comment]
Thank you. Works perfectly!

**Comment by vsha041** [comment]
Just so that this will be helpful for others. We did an upgrade to .NET 6.0 but didn't upgrade AutoMapper library. AutoMapper was 8.1.1 and AutoMapper.Extensions.Microsoft.DependencyInjection was 6.0.0. We got the same error. After debugging, it turned out the reason is because our API loads EntityFrameworkCore.CommonTools version 2.0.2 which references Microsoft.EntityFrameworkCore version 2.0.2 but because of .NET 6.0 upgrade, the process is loading Microsoft.EntityFrameworkCore version 6.0.14 and when AutoMapper tries to find all [DefinedTypes](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.assembly.definedtypes?view=net-7.0) of the Microsoft.EntityFrameworkCore version 2.0.2, one of them is Microsoft.EntityFrameworkCore.Query.Internal.IAsyncQueryProvider which was supposed to be in Microsoft.EntityFrameworkCore version 2.0.2 but now is moved to a different namespace in 6.0.14. 

The workaround was to just not load the type by doing this intead 

`services.AddAutoMapper(AppDomain.CurrentDomain.GetAssemblies().Where(x => string.Equals(x.GetName().Name, "EntityFrameworkCore.CommonTools") == false));`
