### ISSUE TITLE
EF Core and Database First: cannot convert error

### ISSUE THREAD

**Issue by thorstenschroeder** [zzzprojects/EntityFramework-Plus#602]
### Description
Based on [this ](https://entityframework-plus.net/ef-core-audit-autosave )documentation I am trying to implement AutoSave audit logging with database-first approach using Entity Framework Core plus audit.

However on the last line (in AddRange) in below code I get an error (see Exception):
```
static EntityContext()
{
      AuditManager.DefaultConfiguration.AutoSavePreAction = (context, audit) =>
         (context as EntityContext).AuditEntries.AddRange(audit.Entries);
}
```

### Exception
`cannot convert from 'System.Collections.Generic.IEnumerable<Z.EntityFramework.Plus.AuditEntry>' to 'MyProject.MyDataModels.AuditEntries'`

Also note that I changed these marked lines:
![grafik](https://user-images.githubusercontent.com/38812723/79729074-3bc85200-82ef-11ea-82d6-1613a9e05104.png)

### Fiddle or Project

Fiddle: based on the default DB first fiddle I created this [fiddle](https://dotnetfiddle.net/sd63TO) which produces the same error.

I also created a test project with code first and sqlite connection where everything works fine. Then from those entities I scaffolded the db and get above error.

I uploaded my test project [here](https://easyupload.io/xz0i40)

### Further technical details
- EF version: latest
- EF Plus version: latest
- Database Provider: SQL Server and sqlite

Hope you can help figure out what I am doing wrong.

**Comment by JonathanMagnan** [comment]
Hello @thorstenschroeder ,

The issue happens because your `Import` should return a `DbAuditEntry` and `DbAuditEntryProperty` type. You currently return the wrong entity type which leads to this error.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by thorstenschroeder** [comment]
Thanks, I did have the wrong return type.
