### ISSUE TITLE
IncludeFilter > Take() not translated in SQL query

### ISSUE THREAD

**Issue by janmarques** [zzzprojects/EntityFramework-Plus#612]
Using .NET Core 2.x (and Z.EntityFramework.Plus.EFCore version 2.0.50).

I noticed that IncludeFilter got very slow on our production. We try limiting the include by adding a Take()-statement, but that doesn't seem to get translated into SQL. So I assume that all the records are transferred to memory and only there the Take() gets executed.

Code:
```
using (var db = new SomeDbContext())
            {
                var classA = db.ClassAs.
                     IncludeFilter(x => x.ClassBs.Where(y => y.SomeProp < (int.MaxValue - 1000)).OrderBy(y => y.Id).Take(5))
                     .Single();
            }
```

SQL:
```
-- EF+ Query Future: 1 of 2
SELECT TOP(2) [c].[Id], [c].[SomeProp]
FROM [ClassAs] AS [c]
;

-- EF+ Query Future: 2 of 2
SELECT [x].[Id], [x].[SomeProp], [x.ClassBs].[Id], [x.ClassBs].[ClassAId], [x.ClassBs].[SomeProp]
FROM [ClassAs] AS [x]
LEFT JOIN [ClassBs] AS [x.ClassBs] ON [x].[Id] = [x.ClassBs].[ClassAId]
ORDER BY [x].[Id]
;
```

A full program is available here: 
https://github.com/janmarques/efplus-failing-take/tree/master/ConsoleApp3

Note that the above DOES work as expected in .NET Core 3 with the corresponding nuget package (Take gets included in SQL), but we cannot currently port our production yet.

**Comment by JonathanMagnan** [comment]
Hello @janmarques ,

Unfortunately, you are currently experiencing an issue with the `Client Side` evaluation in EF Core 2 (which has been removed in EF Core 3).

The "Take" is done on the client side, so no SQL was generating by EF Core. Therefore, our library don't see it either.

There is currently nothing we can do, as you stated this issue is solved in EF Core 3 since it do not longer do any more client-side evaluation.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by janmarques** [comment]
Hi Jonathan

ok thanks for having a look and clarifying where the issue lays.

-Jan
