### ISSUE TITLE
Method Not Found when delete. Using preview 6 of .NET Core 5.

### ISSUE THREAD

**Issue by DPiaz** [zzzprojects/EntityFramework-Plus#615]
I am having a similar issue to #604 , but on preview 6 of .NET Core 5.

```
'Method not found: 'Void Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor..ctor(Microsoft.EntityFrameworkCore.Query.IEvaluatableExpressionFilter, Microsoft.EntityFrameworkCore.Query.IParameterValues, System.Type, Microsoft.EntityFrameworkCore.Metadata.IModel, Microsoft.EntityFrameworkCore.Diagnostics.IDiagnosticsLogger`1<Query>, Boolean, Boolean)'.'
at .(IQueryable , RelationalQueryContext& , QuerySqlGenerator& )\r\n   
at Z.EntityFramework.Extensions.BatchDelete.CreateCommand(IQueryable query, IEntityType entity)\r\n   
at Z.EntityFramework.Extensions.BatchDelete.Execute[T](IQueryable`1 query)\r\n   
at Z.EntityFramework.Plus.BatchDeleteExtensions.Delete[T](IQueryable`1 query, Action`1 batchDeleteBuilder)\r\n   
at Z.EntityFramework.Plus.BatchDeleteExtensions.Delete[T](IQueryable`1 query)\r\n   
at KratorLab.Services.EntityService.DeleteEntity(Guid id) in D:\\Lab\\Krator\\KratorLab\\Services\\EntityService.cs:line 114"
```

My code:

```
appDbContext.EntityRelationships
    .Where(r => r.Id == relationship.InverseRelationship.Id)
    .Delete();
```

**Comment by JonathanMagnan** [comment]
Hello @DPiaz ,

Thank you for reporting, we had already a task planned this weekend to check the compatibility with the latest preview version.

It should be fixed by the start of next week,

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by DPiaz** [comment]
Ok, thanks.

**Comment by JonathanMagnan** [comment]
Hello @DPiaz ,

A new version has been released which support the latest preview of EF Core 5,

Let us know if everything works as expected.

Best Regards,

Jon

**Comment by DPiaz** [comment]
Hi.

Great, now this works.
Thanks.
