### ISSUE TITLE
System.Exception:“Oops! An error occurred when reading your model. A duplicate key has been found when adding value to a dictionary. Please report the issue to our support team: info@zzzprojects.com;Dictionary ID=Index_EntityTypes_Name;Key=Max_Id;Value=Z.EntityFramework.Extensions.Core.SchemaObjectModel.SchemaEntityType”

### ISSUE THREAD

**Issue by Slhaos7373** [zzzprojects/EntityFramework-Plus#617]
System.Exception:“Oops! An error occurred when reading your model. A duplicate key has been found when adding value to a dictionary. Please report the issue to our support team: info@zzzprojects.com;Dictionary ID=Index_EntityTypes_Name;Key=Max_Id;Value=Z.EntityFramework.Extensions.Core.SchemaObjectModel.SchemaEntityType”

**Comment by JonathanMagnan** [comment]
Hello @Slhaos7373 ,

Do you think you could provide us your model? This kind of issue is only debuggable when we receive the model.

Here is the instruction on how to provide it: https://entityframework-extensions.net/edmx

You can send it in private here: info@zzzprojects.com

It has been a long time since this issue happened. It usually happens because we either do not support yet something special your model has, or your model might have an error.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @Slhaos7373 ,

Since our last conversation, we haven't heard from you. 

As mentioned in my previous message, you can send your model to our mailbox: info@zzzprojects.com 

Looking forward to hearing from you, 

Jon
