### ISSUE TITLE
EF Plus LINQ Dynamic vs System.Linq.Dynamic.Core

### ISSUE THREAD

**Issue by bcronje** [zzzprojects/EntityFramework-Plus#618]
### Description
What is the difference between the EF Plus LINQ Dynamic feature and the standalone [Dynamic LINQ](https://dynamic-linq.net/) library? Both seems to be from the same maintainer.

Is the recommendation on new projects to stick with EF Plus for dynamic linq features?

**Comment by JonathanMagnan** [comment]
Hello @bcronje ,

Both have different syntax. One good example is how the `OrderBy` work in both libraries

Normally, the order by have the following syntax:

```csharp
var ordered = context.Customers
             .OrderBy(c => c.City).ThenBy(c => c.CompanyName)
             .ToList();
```

## Dynamic Linq (from `C# Eval Expression`)

_The C# Eval Expression library is a paid but the LINQ part is free_

The syntax is similar to C# language. It's the more powerful of both libraries:

```csharp
var ordered = context.Customers
             .OrderByDynamic("c => c.City").ThenBy("c => c.CompanyName")
             .ToList();
```

This library doesn't only work with LINQ but with everything you wish to evaluate dynamically at runtime.

## Dynamic Linq (`System.Linq.Dynamic.Core`)

Use more a friendly syntax and the most popular of both librairies. Easier to write/use but less flexible:

```csharp
var ordered = context.Customers
             .OrderBy("City, CompanyName")
             .ToList();
```

https://dynamic-linq.net/basic-simple-query#ordering-results

A lot of very cool operators exists in this library which is not part of the C# Language: https://dynamic-linq.net/expression-language#operators

---

Both work and I do not believe have any conflict to be used together.

From my point of view, I would stick with the one provided in EF Plus (so  `C# Eval Expression` library) as I prefer to follow the C# syntax but both libraries is a good choice so the only thing I could recommend you is to try both and stick with the one you prefer.

I believe that's more a personal choice since both libraries are maintained by us and have their pros/cons

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by bcronje** [comment]
Thank you @JonathanMagnan 

I'm specifically interested in using dynamic OrderBy clauses and have used `System.Linq.Dynamic.Core` successfully in other projects and that worked perfectly. However in this new project I also have a need to EF Plus Future/Deferred functionality, so it might just be easier to stick with EF Plus instead of running both libraries.

Just to confirm, if I use EF Plus with OrderByDynamic functionality, that is part of the free functionality of `C# Eval Expression` ?

**Comment by JonathanMagnan** [comment]
Yes, all LINQ method is free.

So I confirm that `OrderByDynamic` is part of the free functionality.

**Comment by bcronje** [comment]
Perfect thank you.
