### ISSUE TITLE
IncludeOptimized() doesn't include the navigation properties that had been cached by FromCacheAsync()

### ISSUE THREAD

**Issue by bisquitthe** [zzzprojects/EntityFramework-Plus#619]
### Description
We have such relation: **User (1)<->(N) AssignedRole (N)<->(1) RoleType** and have code like that
1. `await dbContext.RoleTypes.FromCacheAsync();`
2. ` await dbContext.Users.IncludeOptimized(a=>a.AssignedRoles)`,
where `AssignedRoles` is `Collection`.
In that case we suppose that `RoleType` is included for every `AssignedRoles` item as well, but they're not.
Also  we noticed that using `await dbContext.RoleTypes.ToArrayAsync();` instead of line **1** does exactly what we need, but in that case the additional request is sent to the database.

### Further technical details
- EF version: Core 3.1
- EF Plus version: 3.0.53
- Database Provider: EfCore.SqlServer

**Comment by JonathanMagnan** [comment]
Hello @bisquitthe ,

`FromCache` use `AsNotTracking` which means all `RoleType` is not in the Change Tracker so are not automatically mapped to AssignedRoles. `FromCache` cannot depend on an existing context, otherwise, you will have some weird behavior depending on if the cache get the `RoleType` from the database (the first time) or from the cache.

The `ToArrayAsync` add role type in the `ChangeTracker`, which means when you retrieve the AssignedRoles, the `RoleType` can be automatically mapped.

Let me know if that explains correctly the current behavior.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by bisquitthe** [comment]
Yes, that's clear to me. Thanks!
