### ISSUE TITLE
What's the difference between "Z.EntityFramework.Plus.EFCore" and  "Z.EntityFramework.Extensions.EFCore"

### ISSUE THREAD

**Issue by stevenxi** [zzzprojects/EntityFramework-Plus#645]
### Description
It's quite confusing that to have "Z.EntityFramework.Plus.EFCore" and  "Z.EntityFramework.Extensions.EFCore" both reference in the project.

There're quite many APIs look same but don't know if they just work the same. For example:
UpdateFromQueryAsync<T>() vs UpdateAsync<T>()  are they the same?

### Exception
If they're the same, is there any plan to retire one.
If not, is there way to avoid confusing?

Thanks.

**Comment by JonathanMagnan** [comment]
Hello @stevenxi ,

Initially, EF Plus and EF Extensions were 2 separated libraries.

EF Plus: Free features
EF Extensions: Paid features

However, over time and with all changes EF Core bring, it was becoming too hard to support everything and we chose to add a dependency on EF Plus to EF Extensions

See the following thread: https://github.com/zzzprojects/EntityFramework-Plus/issues/510

There is indeed a few methods that are duplicated (`Delete` & `DeleteFromQuery`, `Update` & `UpdateFromQuery`). We might eventually bring down `Delete` and `Update` method but at this moment, we have currently no plan to do it since even if it removes some confusion, they are not still 100% the same (for EF Core, they are pretty much the same if not the same but for EF6, they don't work at all the same way).

Let me know if that answer correctly to your question.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by stevenxi** [comment]
Thanks @JonathanMagnan ,

So do you recommand use .DeleteFromQuery() instead of .Delete()?  

Thanks.

**Comment by stevenxi** [comment]
Sorry, didn't se the link of #510.

It fully make sense.  Thanks
