### ISSUE TITLE
Feature: DisplayName

### ISSUE THREAD

**Issue by sven5** [zzzprojects/EntityFramework-Plus#67]
Hi,

it would be great to use DisplayNames (e.g. from DisplayAttribute) for entity names and property names. That way end users can see Audit trails with speaking names.

Regards
Sven

**Comment by zzzprojects** [comment]
Thank you for this great suggestion.

**Comment by zzzprojects** [comment]
Hello @sven5 ,

The DisplayName attribute is currently under development,

There is still some work to do, but so far, we very happen with this new changes

It should be available on Monday. I will let you know as soon as the new version is ready.

Best Regards,

Jonathan

**Comment by sven5** [comment]
Hi Jonathan,

I'm looking forward. Thank you

Sven

**Comment by zzzprojects** [comment]
Hello @sven5 ,

The v1.4.10 is now available.

However, Display DataAnnotation are not automatically added since they may be a little bit "time consuming."

I still want to improve this feature, but so far you can achieve the result like this:

Audit Display

```csharp
[AuditDisplay("MyEntity")]
public class Entity
{
	[AuditDisplay("MyID"]
	public int ID { get; set; }
}

audit.Configuration.DataAnnotationDisplayName();
```

The "DataAnnotationDisplayName" will probably be changed for something like "DisplayDataAnnotation" to follow the same convention as ExcludeDataAnnotation and IncludeDataAnnotation.

Let me know if this solution works for you and if you have a better idea how to name these methods ;)

Best Regards,

Jonathan

**Comment by zzzprojects** [comment]
Closing: Request Done

**Comment by JGKL** [comment]
Hello @ghost, how could I use the `[AuditDisplay("")]` when using EFCore and not EF6..

**Comment by JonathanMagnan** [comment]
Hello @JGKL ,

Please make your own issue (by referencing this one if needed), it makes it easier on our side to follow them.

Best Regards,

Jonathan
