### ISSUE TITLE
Using cached entities on navigation properties from another DbContext

### ISSUE THREAD

**Issue by esnz** [zzzprojects/EntityFramework-Plus#674]
Sorry but this may be an obvious issue and might have been discussed before but searching through issues I couldn't find any.

The issue is that I don't use a single DbContext across the entire application so, at application startup, I simply cache the required entities, however whenever I assigned any of those cached entities to a navigation property of an entity in another DbContext they get duplicated by EntityFramework when SaveChanges is called as they belong to another context and EF thinks they are newly attached entities and do not exist in the database, Is this a limitation or there is a solution to overcome this problem or a way to transfer the cached entities to the new DbContext?

**Comment by JonathanMagnan** [comment]
Hello @esnz ,

Cached entities are disconnected entities (so no attached to any `DbContext`).

While you can still do it, you normally don't want to attach them and perform `Save Operations` on them. You want to use it like read-only entities. Cached entities are to be used globally, so it makes no sense to attach them from a specific context, otherwise, other contexts could not use them.

So this is not a limitation but exactly an expecting behavior since they are disconnected. There is currently no way to transfer those entities since that's not how they should be used.

Let me know if that answers correctly to your question.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by esnz** [comment]
Hi @JonathanMagnan,
Thanks for the detailed explanation, this made a lot of sense. As a workaround, I just now use Primary Keys from cached Entities instead of assigning them to navigation properties and it gets the job done.
Thanks!
