### ISSUE TITLE
Hight CPU usage when using Future Queries

### ISSUE THREAD

**Issue by gabmilg** [zzzprojects/EntityFramework-Plus#677]
## 1. Description
While stress testing an endpoint I have experienced  high CPU usage when using Future Queries it almost twice vs separate roundtrips to db.
Is it expected behavior ?

## 2. Sample code:

using query Future 

```
var f1= _dbContext.Entity_1.Future();
var f2= dbContext.Entity_2.Future();

var f1Result= await f1.ToArrayAsync();
var f2Result= await f2.ToArrayAsync();
```

VS standard (2 roundtrips)

```
var result1 = _dbContext.Entity_1.ToArrayAsync();
var result2 = dbContext.Entity_2.ToArrayAsync();
```

![pp](https://user-images.githubusercontent.com/41384302/112507127-c5d13400-8d64-11eb-8ac8-86e340a71d5c.JPG)

## 3. Any further technical details
SQL Server 2012
EFCore 5.0.4
.NET 5.0 WebApi
z.entityframework.plus.efcore.5.1.26

**Comment by JonathanMagnan** [comment]
Hello @gabmilg ,

Besides adding a comment, our library doesn't change the SQL generated.

It only batches them in **one** SQL Command instead of executing them in multiple commands.

We tried on our side and on the SQL side, it was pretty much always faster. We tried to check the application CPU but we didn't see any major difference.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)
