### ISSUE TITLE
Transaction (Process ID) was deadlocked on lock resources with another process and has been chosen as the deadlock victim

### ISSUE THREAD

**Issue by ooples** [zzzprojects/EntityFramework-Plus#678]
I started to receive these errors around 4 or 5 versions ago and I had thought that it was caused by my coding but I looked further into the issue based on the steps at [this website](https://sqlbak.com/academy/transaction-process-id-was-deadlocked-on-lock-resources-with-another-process-and-has-been-chosen-as-the-deadlock-victim-msg-1205) and below is an example of a full deadlock report showing that it is actually being caused by your code, specifically the bulk merge that I'm using. I have thousands of copies of this report with the same exact info btw

[Full deadlock report](https://pastebin.com/5sUnwEQv)

I have code that I can email you if needed

**Comment by JonathanMagnan** [comment]
Hello @ooples ,

This problem always has been part of our library due to how SQL Server works with `MERGE` statement with concurrency scenario. Unfortunately deadlock is still way to easy to happen ;(

If it's possible for you, one solution could be simply to lock the table per a single BulkMerge:

```csharp
context.BulkMerge(list, options => options.UseTableLock = true);
```

There is nothing more we can really do on our side and unfortunately, we cannot force this lock by default.

I might be wrong but I believe you currently call `BulkMerge` in concurrency for every stock in your list to save the full/partial history. So using `TableLock` should solve the issue, you can also find out if that's possible for you to call this `BulkMerge` only once or if the concurrency is really necessary in your case.

**Comment by ooples** [comment]
I'm afraid the table lock won't work for me because I have hundreds of threads each downloading information and performing calculations on it together. I will try to find an alternate to bulk merge then. One thing I did notice though is that I recently downgraded your api to the latest release version and I haven't had the issue yet

**Comment by JonathanMagnan** [comment]
That's weird, which version have you downgraded to? I do not believe any change has been done about how to SQL is generated but we will at least look at it.

**Comment by ooples** [comment]
I downgraded to 5.1.30 and I have yet to see any of the errors since
downgrading

**Comment by JonathanMagnan** [comment]
Hello @ooples ,

Since we haven't found any abnormal about this request, it will remain closed. 

However, you can always contact us if you find anything!

Best regards,

Jon
