### ISSUE TITLE
error while trying to use BulkUpdate on .Net Core 3.1

### ISSUE THREAD

**Issue by jiveshpkuniyil** [zzzprojects/EntityFramework-Plus#679]
Here is what to include in your request to make sure we implement a solution as quickly as possible. 

## 1. Description

```
When using BulkUpdate in .Net Core 3.1 it throws error.

//This doesn't work
using (var admindb = new AdminDb())
                {
                    var roles = admindb.Role.Where(item => item.Id == parentId).Select(a => a).AsQueryable();
                    admindb.BulkDelete(roles);                    
                }

```
## 2. Exception
ERROR_005: The monthly trial period is expired. You can extend your trial by downloading the latest version as the beginning of every month. More information can be found here: https://entityframework-extensions.net/trial

```
Exception message:
Stack trace:
```

## 3. Fiddle or Project
EFPlusConversion.zip

Otherwise, make sure to include as much information as possible to help our team to reproduce the issue.

## 4. Any further technical details

EF version: Microsoft.EntityFrameworkCore(3.1.0)
EF Plus version: Z.EntityFramework.Plus.EFCore(3.0.58)
Database Provider: Pomelo.EntityFrameworkCore.MySql(3.1.0)

**Comment by JonathanMagnan** [comment]
Hello @jiveshpkuniyil ,

Make sure to check on this page about what features are free and what is paid: https://entityframework-plus.net/download

Pretty much everything with `Bulk` in the name is enterprise features that require a license.

That's why you are currently getting this exception.

You can also force an error as soon as a paid feature is used with the following code (again in the download page):

```txt
To automatically throw an error when using a paid features, use `EntityFrameworkManager.IsCommunity = true`
```

Let me know if that explains correctly why you are getting this exception or your problem is something else (you zip file have not been uploaded correctly so I cannot check it)

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)
