### ISSUE TITLE
Feature: Attributes for excluding/including

### ISSUE THREAD

**Issue by sven5** [zzzprojects/EntityFramework-Plus#68]
Hi,

it would be very useful if one can decorate properties/classes with attributes to exclude or include them in audit trails. The attribute could also be used to define DisplayName for the property or entity.

Regards
Sven

**Comment by zzzprojects** [comment]
Thank you for this great suggestion.

**Comment by zzzprojects** [comment]
Hello @sven5 ,

The Exclude/Include attribute is currently under development,

There is still some work to do, but so far, we very happen with this new changes

It should be available on Monday. I will let you know as soon as the new version is ready.

Best Regards,

Jonathan

**Comment by sven5** [comment]
Hi Jonathan,

That's great news. 

Thanks

**Comment by zzzprojects** [comment]
Hello @sven5 ,

The v1.4.10 is now available.

However, Exclude/Include DataAnnotation are not automatically added since they may be a little bit "time consuming."

I still want to improve this feature, but so far you can achieve the result like this:

**Audit Exclude**
```csharp
[AuditExclude]
public class Entity
{
}

audit.Configuration.ExcludeDataAnnotation();
```

**Audit Include**
```csharp
[AuditInclude]
public class Entity
{
}

// Exclude All
audit.Configuration.Exclude(o => true);
audit.Configuration.IncludeDataAnnotation();
```

Let me know if this solution works for you and if you have a better idea how to name these methods ;)

Best Regards,

Jonathan

**Comment by zzzprojects** [comment]
Closing: Request Done
