### ISSUE TITLE
BulkInsert DataTable from C# to Postgres gives error

### ISSUE THREAD

**Issue by benberlin7** [zzzprojects/EntityFramework-Plus#698]
## 1. Description
I have a "System.Data.DataTable" with 71 cols (1 int PK, the others SINGLE/FLOATs) and want to bulkinsert this datatable to postgres (via docker, it runs well, other executecommands work and pgadmin shows changes). 
However, when I want to bulkinsert the table (which has no NULL values inside and no duplicate PKs, col names are matching) I get the following error : 

## 2. Exception

Exception message:
Stack trace:
: 'System.Exception: An error occured while retrieving the InformationSchemaTable information. See the inner exception for details.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](List`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)   
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at ?.?(Boolean ?, String[] ?)
   at ?.?()
   at Z.BulkOperations.BulkOperation.?()
   --- End of inner exception stack trace ---

## 3. Code

var cs = "Host=" + addr + ";Username=postgres;Password=pw;Database=postgres";
var tablename = "test";
System.Data.DataTable table = new DataTable(tablename);
-> filling the table...

using (var con = new NpgsqlConnection(cs))
                           {
                                con.Open();
                                var bulk = new BulkOperation(con);
                                bulk.BulkInsert(table);
                            }
                        }

## 4. Any further technical details
Win10, VS Pro, NetFramework

**Comment by JonathanMagnan** [comment]
Hello @benberlin7 ,

Could you provide your table definition or a runnable project that we can run and throw the error?

If needed, you can send it in private here: info@zzzprojects.com

The issue seems to happen when we try to get some information from your table in PostgreSQL.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @benberlin7 ,

My developer told me the current issue happen because since table and column name are not escaped, PostgreSQL put everything in lowercase. So when our library tries to find the table `Plant` it doesn't find it since the name is `plant`. 

I will ask him to check a little bit more about it since I find it weird that we throw this error instead of a custom one.

**Comment by benberlin7** [comment]
It works now - thank you!
Sometimes it's a simple fix :-)
---
Doesn't belong to this issue, but I was wondering if there is room for performance optimization? Because with this bulk postgre takes 14seconds, while other DB's take ~8s for the same task.

**Comment by JonathanMagnan** [comment]
Hello @benberlin7 ,

There is always some room for performance optimization but since we need to be generic, this is always harder on our side.

I don't think anything will be done in performance directly for `PostgreSQL` for now, but indirectly, we still improve often our library to use less `Entity Framework` method for optimizing the overall performance.

Best Regards,

Jonathan
