### ISSUE TITLE
Performance Problem when Using Future

### ISSUE THREAD

**Issue by jimalbert19** [zzzprojects/EntityFramework-Plus#707]
We are using EntityFramework-Plus Core (5.13.0) and EntityFramework Core 5.x. We are using the "Future" extension method when we want to improve performance fetching from the database. We also would like to use lazy loading at times that performance is not an issue and there are a large number of related items. Everything works fine except in one case... 

Assume that we have a db table that is Books and a Book has Chapters and execute this code ...

var linq = from bin ctx.Books select b;
linq = linq.Future();
var linq1 = linq.SelectMany(x => x.Chapters).Future();

var books = linq.ToList();

Running this code will fetch all the books and fill in the chapters for the books that have chapters. The problem is that if there are books that do not have any chapters the collection of chapters for those books will be left as null. When the code accesses the chapters collection for these books because the collection is null, lazy loading  will kick in and try to refetch the chapters. There are not chapters and the collection will be set to an empty collection. The problem is that this kills the performance.

Is there a way to have the empty collections set to empty collections (not left as null) so lazy loading will not fetch or is there a better way to accomplish what I am trying to do?

Thanks.

**Comment by JonathanMagnan** [comment]
Hello @jimalbert19 ,

This issue seems to be out of the scope of the `Future` feature. It is more related of how the ChangeTracker and Lazy Loading work.

Is there a reason why you don't just use a simple `Include` that will solve this issue?

You can also use `AsSplitQuery` to optimize the performance if you need 2 queries to be executed.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by jimalbert19** [comment]
Thanks. I ended up switching to using the IncludeOptimized and that fixed my issue.
