### ISSUE TITLE
EntityFramework-Plus dependency on Z.Expressions.Eval is set to Equal but Z.Expressions.Eval is typically newer

### ISSUE THREAD

**Issue by KayakFisher205** [zzzprojects/EntityFramework-Plus#717]
## 1. Description
I notice when I update nugets, typically see a warning after a compile about Z.Expressions.Eval being a greater version.

## 2. Exception
warning NU1608: Detected package version outside of dependency constraint: Z.EntityFramework.Plus.EF6 6.13.7 requires Z.Expressions.Eval (= 4.0.71) but version Z.Expressions.Eval 4.0.72 was resolved.

Is there a specific reason its not =>4.0.71 like some of the other dependencies. Its not a show stopper or anything like that. Its just shows up as a warning.

**Comment by JonathanMagnan** [comment]
Hello @KayakFisher205 ,

Is probably to some issue reported like this one: https://github.com/zzzprojects/EntityFramework-Plus/issues/673

Some people that were using a different version of the dependencies (higher) had some problems due to the version not matching. 

Since we release pretty much around 1-2 weeks, we just find out the easiest solution for us was forcing a specific version.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)
