### ISSUE TITLE
Use NLog for logging query in EF Core Plus

### ISSUE THREAD

**Issue by petrkasnal** [zzzprojects/EntityFramework-Plus#733]
Hi,

is any way how to use nlog for loggin query? Or is any way how to do it yourself? 

Thank you :)

**Comment by JonathanMagnan** [comment]
Hello @petrkasnal ,

We do not directly support NLog,

There is some way to log via EF Interceptor or directly with some events in some methods, but the answer depends highly on which method you are using.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by petrkasnal** [comment]
@JonathanMagnan Ok thank you. Do you think you'll ever add it? Existst any global interceptor where i can log queries? Thanks

**Comment by JonathanMagnan** [comment]
Hello @petrkasnal ,

There is no short-term plan for doing it at this moment. I don't think it will ever be done as is seem we have too many task in our backlog.

Best Regards,

Jon

**Comment by petrkasnal** [comment]
Hello @JonathanMagnan ,

ah ok. But i think this is important thing. Because how i can know testing queries. And my question again is here any solution how to do it? Any global interceptor or something like this.

Thank you

**Comment by petrkasnal** [comment]
Hello @JonathanMagnan,

Can you please respond? Exists any global interceptor?

Thank you

**Comment by JonathanMagnan** [comment]
Hello @petrkasnal ,

Unfortunately, no, there is no global interceptor.

**Comment by petrkasnal** [comment]
Hello @JonathanMagnan,

aaa ok. 

Thank you :)

**Comment by snakefoot** [comment]
Since EF Core uses Microsoft Extension Logging should all logging not be available unless filtering away "Microsoft.EntityFrameworkCore"-output (Notice by default Microsoft-LoggerFactory will filter all output for logger-category "Microsoft").

See also: https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/

See also: https://stackoverflow.com/questions/43680174/entity-framework-core-log-queries-for-a-single-db-context-instance

Notice NLog.Extensions.Logging v5 includes a "breaking change" where it ignore any filtering in Microsoft LoggerFactory.
