### ISSUE TITLE
[Question] Context Disposed when running on Azure Functions

### ISSUE THREAD

**Issue by goncalo-teixeira** [zzzprojects/EntityFramework-Plus#751]
Currently I have an Azure Function running on an Elastic Premium Function App inserts in the database using EntityFramework-Plus.  Currently the behaviour is that the function will work for a while flawelessly. Then in a random execution I will get the following error message: Error : `at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed() at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices() at Microsoft.EntityFrameworkCore.DbContext.get_ChangeTracker() at Sonae.MailManager.Infrastructure.Persistence.ApplicationDbContext.<.ctor>b__2_2(DbContext context) in D:\a\1\s\Sonae.MailManager.Infrastructure\Persistence\ApplicationDbContext.cs:line 67 at DbContextExtensions.(DbContext this, Action`1 , DbContext ) at .BulkInsert[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping) at .BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges) at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options) at System.Threading.Tasks.Task.InnerInvoke() at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj) at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location --- at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) --- End of stack trace from previous location --- at DbContextExtensions.BulkInsertAsync[T](DbContext this, IEnumerable`1 entities, Action`1 options, CancellationToken cancellationToken) at Sonae.MailManager.Infrastructure.Services.MailboxExchangeService.ProcessByFolderAsync(ILogger log, IMailFolder folder, IMailFolder toProcessFolder, IMailFolder processedFolder, IMailFolder errorFolder, IMailFolder outboxFolder, Int32 mailboxId, Int32 folderId, Int32 outboxId, MailboxProcess process, MailboxSettingsDTO mailboxSettings, IEnumerable`1 allMessages, Dictionary`2 errors, Dictionary`2 toprocess, Dictionary`2 successes, Int32 countSuccess, Int32 countError) in D:\a\1\s\Sonae.MailManager.Infrastructure\Services\MailboxExchangeService.cs:line 457 at Sonae.MailManager.Infrastructure.Services.MailboxExchangeService.ProcessInbox(Int32 mailboxId, ILogger log, CancellationToken cancellationToken) in D:\a\1\s\Sonae.MailManager.Infrastructure\Services\MailboxExchangeService.cs:line 153`

Requests made by regular entity framework succed but when a zentity framework is called I get this message.
Any Ideas of what is causing this problem?

**Comment by JonathanMagnan** [comment]
Hello @goncalo-teixeira ,

We currently have no idea why this error is currently happening. Obviously, we know this error happens because the context is disposed (https://github.com/dotnet/efcore/blob/main/src/EFCore/DbContext.cs#L473) but why it's considered disposed is another story.

One common cause might be the missing `await` keyword.

Such as, the following code will throw this error:

```csharp
using (var context = new EntityContext())
{
	// would be the same problem with `SaveChangesAsync`
	// context.SaveChangesAsync();
	
	context.BulkInsertAsync(list);
}
```

As the context might be disposed of during the time the `Async` method gets executed. The following code should be used instead:

```csharp
using (var context = new EntityContext())
{
	// with or without `ConfigureAwait(false)` depending of your application
	// await context.SaveChangesAsync();
	
	await context.BulkInsertAsync(list);
}
```

So in this case, the `BulkInsertAsync` will be completed before the context get disposed

Could it be your problem?

Otherwise, do you think you could create a runnable project with the issue? It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue. You can send it in private here: info@zzzprojects.com

Best Regards,

Jon
