### ISSUE TITLE
Batch Update method pass wrong DateTime.Now param.

### ISSUE THREAD

**Issue by wangshuai-007** [zzzprojects/EntityFramework-Plus#755]
Here is what to include in your request to make sure we implement a solution as quickly as possible. 

## 1. Description
My Batch Update code is like this:
```c#
await _context.StudyVideos.Where(w => listIds.Contains(w.Id)).UpdateAsync(c =>
                            new StudyVideo()
                            {
                                Status = status,
                                UpdateTime = DateTime.Now,
                                PublishTime = status == PublishStatus.Publish ? DateTime.Now : c.PublishTime,
                                UpdateUserId = userId
                            })
```
It will get the follow SQL
```SQL
UPDATE "studyvideo"
SET "status" = @zzz_BatchUpdate_0,
"updatetime" = @zzz_BatchUpdate_1,
"publishtime" = now(),--error
"updateuserid" = @zzz_BatchUpdate_3
WHERE EXISTS ( SELECT 1 FROM (SELECT xxxx
FROM studyvideo AS s
WHERE s.id = ANY (@__listIds_0)) B
               WHERE "studyvideo"."id" = B."id"
           )
```
## 2. Exception
The error is all my date in database is not UTC.
so `@zzz_BatchUpdate_1` is not equals `now()`

I have to write more code like this
```c#
if (status == PublishStatus.Publish)
{
//...
PublishTime = DateTime.Now,
}
else
{
//...
PublishTime = c.PublishTime,
}

```

## 4. Any further technical details
My DLL is `Z.EntityFramework.Plus.EFCore` version `5.15.0`

**Comment by JonathanMagnan** [comment]
Hello @wangshuai-007 ,

If I understand correctly, to solve this issue, you should declare a date variable outside of the expression such as:

```csharp
var publishTime = DateTime.Now; // or the exact way you want it to be saved in your database

await _context.StudyVideos.Where(w => listIds.Contains(w.Id)).UpdateAsync(c =>
                            new StudyVideo()
                            {
                                Status = status,
                                UpdateTime = DateTime.Now,
                                PublishTime = status == PublishStatus.Publish ? publishTime : c.PublishTime,
                                UpdateUserId = userId
                            })
```

The SQL will now take directly the value from the `publishTime` instead of using `Now`

Let me know if that solved your issue.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/)
