### ISSUE TITLE
Getting OldValue and NewValue of an Audit entities property every time even though the entity has been modified

### ISSUE THREAD

**Issue by mdodevski** [zzzprojects/EntityFramework-Plus#759]
I am using the EntityFramework Plus Audit package: [docs here][1]

I have implemented the following code in my dbContext.

Overload of the ``SaveChanges()``:
```
    public override int SaveChanges()
    {
        var audit = new Z.EntityFramework.Plus.Audit
        {
            Configuration =
            {
                IgnorePropertyUnchanged = false
            }
        };
        
        audit.PreSaveChanges(this);
        var rowsAffected = base.SaveChanges();
        audit.PostSaveChanges();
        
        if (audit.Configuration.AutoSavePreAction == null)
        {
            return rowsAffected;
        }
        
        audit.Configuration.AutoSavePreAction(this, audit);

        base.SaveChanges();

        return rowsAffected;
    }
```

This is my config in the constructor: 
```
    public TimedWorkflowDbContext(DbContextOptions options) : base(options)
    {
        AuditManager.DefaultConfiguration.IgnoreEntityUnchanged = false;
        AuditManager.DefaultConfiguration.Exclude<TimedWorkflowActivity>();
        
        AuditManager.DefaultConfiguration.AutoSavePreAction = (context, audit) =>
        {
            audit.Entries.ForEach(x=> x.CreatedDate = DateTime.UtcNow);
            (context as TimedWorkflowDbContext)?.AuditEntries.AddRange(audit.Entries);
        };

    }
```

Now what my problem is: The entities properties whether updated or not, the oldValue and the newValue are the same.
[![enter image description here][2]][2]

  [1]: https://entityframework-extensions.net/audit
  [2]: https://i.stack.imgur.com/EVCoe.png

I know I have ``IgnorePropertyUnchanged = false``, but if I remove this then only the Id(key) gets audited and written in the database as an audit property.

What could be the problem?

**Comment by JonathanMagnan** [comment]
Hello @mdodevski ,

One common problem is that the entity gets attached instead of being retrieved from the database. When an entity gets attached, the state manager is not aware of the old value.

Something similar to: https://github.com/zzzprojects/EntityFramework-Plus/issues/8#issuecomment-222166610

Let me know if that was indeed the right cause of the problem or if you believe this is something else.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/)
