### ISSUE TITLE
Strange error after updating .Net to 8.0 Preview 7

### ISSUE THREAD

**Issue by srdjo** [zzzprojects/EntityFramework-Plus#775]
After updating the Blazor Server project from .Net Preview 7 to Preview 8 I am getting a strange error

Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit '4frI1lrCAF33gHyoMx1xi36umIsBr5tIYzZncPMxIl4'.
      System.MissingMethodException: Method not found: 'System.Collections.Generic.IEnumerable`1<Microsoft.EntityFrameworkCore.Metadata.IProperty> Microsoft.EntityFrameworkCore.Metadata.IEntityType.GetProperties()'.
         at Z.EntityFramework.Extensions.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
         at BatchUpdateExtensions.UpdateFromQuery[T](IQueryable`1 query, Expression`1 updateFactory, Action`1 batchUpdateBuilder)
         at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory, Action`1 batchUpdateBuilder)
         at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory)

I have the Latest prerelease 8.0.0-preview.5.23280.1-02 of Z.EntityFramework.Extensions.EFCore installed.

What might be the problem ?

**Comment by JonathanMagnan** [comment]
Hello @srdjo ,

At this moment, we only support up to EF Core 8 - Preview 6,

We already have a branch that supports Preview 7 which will be released tomorrow or, more likely next week.

The problem is due that EF Core `preview 7` moved/renamed a few methods that we were using.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/)

**Comment by JonathanMagnan** [comment]
Hello @srdjo ,

The latest version released today should now support the `Preview 7`: https://www.nuget.org/packages/Z.EntityFramework.Plus.EFCore/8.0.0-preview.7.23375.4-01

If you have the chance to try it, let us know if everything is now working as expected.

Best Regards,

Jon

**Comment by srdjo** [comment]
It works great. Thanks a lot
