### ISSUE TITLE
SingleOrDefault() with IncludeOptimized returns the first item for not single collection

### ISSUE THREAD

**Issue by magicmanam** [zzzprojects/EntityFramework-Plus#822]
Hi guys!

Is it expected that SingleOrDefault() method returns the first element for IQueryable object returned by IncludeOptimized WHEN collection contains more than one element? I didnt find anything about it on your site and was a little bit confused.

https://dotnetfiddle.net/qk5l1f

My expectation here is to see InvalidOperationException thrown.

**Comment by JonathanMagnan** [comment]
Hello @magicmanam ,

Thank you for reporting.

We will see if there is something we can do about it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @magicmanam ,

After investigating, due to how our library is made, we will not be able to support this combination. This is more complex as we don't control everything on our side, and a lot of logic is done on the EF side.

You can somewhat use a trick on your side, but I don't recommend it even if it's working:

```csharp
var t = context.EntitySimples.IncludeOptimized(x => x.Child).Take(2).ToList().SingleOrDefault();
```

Best Regards,

Jon

**Comment by magicmanam** [comment]
Hello @JonathanMagnan! Thanks for the answer!

Maybe it makes sence to add a remark to `IncludeOptimized` method's annotation and/or mention about this behavior in the documentation?

Anyway, feel free to close this issue. Thanks!

**Comment by JonathanMagnan** [comment]
Hello @magicmanam ,

Thank you for your suggestion. I added a text about this in the limitations section and referenced this issue.

Best Regards,

Jon
