### ISSUE TITLE
Database Error in SaveChanges() in Combination with .FromCache()

### ISSUE THREAD

**Issue by bernd70** [zzzprojects/EntityFramework-Plus#95]
Hi,

I started to use EntityFramework-Plus and on my first attempt I got an error I do not understand.

I spawn a new DbContext to edit an object (say Course) which can have related entites. When initializing an grid to pick the relation (say Student) I show a complex list of entities I want to cache. For showing the grid I need to include numerous relations to get the display names. So my call looks somehow like this:

ctx.Students.Include(x => x.Faculty.Name).Include(x => x.SubscribedCourses.Selected(y => y.Course).OrderBy(x => x.LastName).ThenBy(x => x.FirstName).FromCache();

This works fine. The first call takes a couple of seconds and all susequent calls are fast.

But when I use some of the entites from the query above and add the to the edited object my SaveChanges() call fails with a primary key contraint violation which is totally unrelated.

Violation of PRIMARY KEY constraint 'PK_dbo.Course insert duplicate key in object...

So SaveChanges() tries to add a Course which is wrong. But I did not add a Course, I only added a Student to a course.

I did check the ChangeTracker entries and it contains all entities loaded from cache, both the Student entity and also all related entites such as Faculty, Course and SubscribedCourse.

Any hints what I am doing wrong?

Regards
Bernd

**Comment by zzzprojects** [comment]
Hello @bernd70 ,

I may be wrong but I don't think this issue is related to our library but how entities are added in the ChangeTracker/DbContext.

In short, Query Cache resolve the query with "AsNoTracking" before adding the result to the cache
```csharp
query.AsNoTracking().ToList();
```

If you do the same without our library, you will still get the same error.

## Change Tracker

### Problem
When you add an entity, entities from navigation properties are also checked/added.

Since the ChangeTracker doesn't know the state of any of these entities it assumes they don't exist! It try to add/insert them which obviously throw a duplicate key.

### Solution
If the user can only edit one row at a time, the best way to handle it is probably getting this entity from the database using the ID and performing the edit.

You will need to expire/refresh this cache every time an edit is performed using the Cache Tag expiration.

Let me know if I answered correctly to your issue.

Best Regards,

Jonathan

**Comment by bernd70** [comment]
Hi Jonathan,

thank you for your answer.

I was not aware that the entites from the cache will not be associated with the DbContext loading them.

So in the scenario I described the Cache will probably make not much sense because typically there are a lot of entites added to the edited object at once.

But I am sure there are other queries in my application where it perfectly makes sense.

Regards
Bernd
